// ── MANTENEDOR LANGUAGE MANAGER ─────────────────────────────────────────────
var LANG = (function(){

var TRANSLATIONS = {

// ── PORTUGUES (padrão) ──────────────────────────────────────────────────
pt: {
  // Navegação
  nav_dashboard:    "Dashboard",
  nav_ordens:       "Ordens de Servico",
  nav_ativos:       "Gestao de Ativos",
  nav_cadastros:    "Cadastros",
  nav_os:           "OS",
  nav_ativos_short: "Ativos",

  // Topbar
  topbar_alert_criticas: " OS critica(s) em aberto",

  // Dashboard — seções
  dash_status:      "Status Operacional",
  dash_confiab:     "Confiabilidade & Disponibilidade",
  dash_gestao:      "Gestao da Manutencao",
  dash_criticidade: "Criticidade dos Ativos (NORSOK Z-008 / API RP 581)",
  dash_ultimas_os:  "Ultimas Ordens",
  dash_equipamentos:"Equipamentos",
  dash_planos:      "Planos com Atencao",
  dash_ver_todas:   "Ver todas →",
  dash_calcular:    "Calcular na ficha do ativo →",
  dash_planos_ok:   "✓ Todos os planos em dia",

  // KPIs
  kpi_abertas:      "OS Abertas",
  kpi_andamento:    "Em Andamento",
  kpi_criticas:     "OS Criticas",
  kpi_equipamentos: "Equipamentos",
  kpi_mtbf:         "MTBF Global",
  kpi_mttr:         "MTTR Global",
  kpi_disponib:     "Disponib.",
  kpi_manuplan:     "Manut. Planejada",
  kpi_compliance:   "Compliance",
  kpi_backlog:      "Backlog",
  kpi_falhas:       "Falhas Corret.",
  kpi_aguardando:   "aguardando",
  kpi_em_exec:      "em execucao",
  kpi_prio_max:     "prioridade max",
  kpi_operando:     "operando",

  // Criticidade
  crit_matriz:      "Matriz de Risco (Consequencia x Probabilidade)",
  crit_ativos:      "Ativos por Criticidade",
  crit_eixo_y:      "Eixo Y: Consequencia",
  crit_eixo_x:      "Eixo X: Probabilidade",
  crit_score:       "Score de Criticidade (0-100)",
  crit_warn_super:  "% dos ativos classificados como Criticos — acima do limite de 30% (NORSOK Z-008). Recalibre os criterios.",
  crit_ok_bench:    "✓ Distribuicao dentro do benchmark (5-15% criticos) — NORSOK Z-008",
  crit_vazio:       'Abra a ficha de cada ativo e calcule a criticidade na aba "Criticidade".',
  crit_mais:        "+mais ",
  crit_avaliados:   " ativos avaliados",
  crit_classes:     {A:"Critico", B:"Alto", C:"Medio", D:"Baixo"},
  crit_recs: {
    A: "Monitoramento continuo (preditiva). Plano de contingencia obrigatorio. FMEA e analise de causa raiz.",
    B: "Preventiva sistematica. Monitoramento por condicao recomendado. Incluir no plano de inspecao.",
    C: "Preventiva baseada em tempo ou ciclos. Avaliar custo-beneficio de preditiva.",
    D: "Corretiva planejada aceitavel (run-to-failure). Garantir sobressalentes disponiveis."
  },

  // Ordens
  ord_titulo:       "Ordens de Servico",
  ord_nova:         "+ Nova OS",
  ord_filtro_todas: "Todas",
  ord_tipo_label:   "Tipo de Manutencao",
  ord_tipo_corr:    "Corretiva",
  ord_tipo_prev:    "Preventiva",
  ord_tipo_pred:    "Preditiva",
  ord_prio_label:   "Prioridade",
  ord_prio_crit:    "Critica",
  ord_prio_alta:    "Alta",
  ord_prio_normal:  "Normal",
  ord_prio_baixa:   "Baixa",
  ord_status_aberta:"Aberta",
  ord_status_and:   "Em Andamento",
  ord_status_conc:  "Concluida",
  ord_status_canc:  "Cancelada",
  ord_iniciar:      "▶ Iniciar Execucao",
  ord_registrar:    "+ Registrar Execucao",
  ord_concluir:     "✓ Concluir OS",
  ord_cancelar:     "✕ Cancelar",
  ord_finalizada:   "OS finalizada",
  ord_sem_prazo:    "Sem prazo",
  ord_atribuida_a:  "OS atribuida a",
  ord_periodo:      "Periodo",
  ord_proxima_em:   "Proxima OS em",
  ord_reg_exec:     "Registro de Execucao",
  ord_sem_reg:      "Nenhum registro ainda",
  ord_inicia_para_reg: "Inicie a OS para comecar a registrar",
  ord_total_pecas:  "em pecas",
  ord_nenhuma:      "Nenhuma OS encontrada",
  ord_nenhuma_cad:  "Nenhuma OS cadastrada",
  // Form labels
  ord_f_titulo:     "Titulo *",
  ord_f_ativo:      "Ativo *",
  ord_f_tipo:       "Tipo",
  ord_f_prio:       "Prioridade",
  ord_f_tecnico:    "Tecnico Responsavel",
  ord_f_prazo:      "Prazo",
  ord_f_periodo:    "Periodo (dias)",
  ord_f_proxima:    "Proxima OS em (dias)",
  ord_f_descricao:  "Descricao / Sintoma",
  ord_f_ativo_label:"Ativo",
  ord_f_abertura:   "Abertura",
  ord_f_tipo2:      "Tipo",
  // Exec log
  exec_tipo_obs:    "Observacao",
  exec_tipo_med:    "Medicao",
  exec_tipo_peca:   "Peca / Material",
  exec_tipo_foto:   "Foto",
  exec_param:       "Parametro medido",
  exec_valor:       "Valor medido *",
  exec_limite:      "Limite / Referencia",
  exec_cond:        "Condicao",
  exec_cond_normal: "Normal",
  exec_cond_atenc:  "Atencao",
  exec_cond_crit:   "Critico",
  exec_cond_fora:   "Fora de especificacao",
  exec_peca_desc:   "Descricao da Peca / Material *",
  exec_qty:         "Quantidade",
  exec_custo:       "Custo unitario (R$)",
  exec_foto_desc:   "Descricao da foto",
  exec_ultimo_reg:  "Ultimo registro",
  exec_qtd_reg:     " registros",

  // Ativos
  at_titulo:        "Gestao de Ativos",
  at_ficha:         "Ficha: ",
  at_novo:          "+ Novo Ativo",
  at_clique:        "Toque em um ativo para abrir a ficha completa",
  at_nenhum:        "Nenhum ativo cadastrado",
  at_tabs: {
    geral:         "Geral",
    indicadores:   "Indicadores",
    historico:     "Historico",
    preventiva:    "Plano de Manutencao",
    preditiva:     "Medicoes",
    documentos:    "Documentos",
    criticidade:   "Criticidade"
  },
  at_info_fabricante: "Fabricante",
  at_info_modelo:     "Modelo",
  at_info_serie:      "Serie",
  at_info_ano:        "Ano",
  at_info_local:      "Localizacao",
  at_info_cat:        "Categoria",
  at_info_tag:        "Tag",
  at_info_pat:        "Patrimonio",
  at_info_empresa:    "Empresa",
  at_info_unidade:    "Unidade",
  at_resumo:          "Resumo & Ultima Intervencao",
  at_intervencoes:    "Intervencoes",
  at_corretivas:      "Corretivas",
  at_horas:           "Horas em Manut.",
  at_ultima_int:      "Ultima Intervencao",
  at_sem_hist:        "Sem registros de manutencao",
  at_sel_ind:         "Selecionar Indicadores",
  at_sel_ind_sub:     "Clique para ativar ou desativar cada indicador neste equipamento.",
  at_nenhum_ind:      "Nenhum indicador ativado. Selecione abaixo.",
  at_reg_manut:       "+ Registrar Manutencao",
  at_registros:       " registro(s)",
  at_sem_manut:       "Nenhuma manutencao registrada ainda.",
  at_novo_plano:      "+ Novo Plano",
  at_nenhum_plano:    "Nenhum plano preventivo cadastrado",
  at_planos_atraso:   " plano(s) com atencao necessaria",
  at_nova_leitura:    "+ Nova Leitura",
  at_sem_leituras:    "Nenhuma leitura preditiva registrada.",
  at_mais_leituras:   "Adicione mais leituras para gerar o grafico",
  at_acima_limite:    "Ultimo valor acima do limite de alerta!",
  at_valor_med:       "Valor medido",
  at_limite:          "Limite",
  at_anexar:          "Clique para anexar documentos",
  at_anexar_sub:      "PDF, Word, Excel, Imagens, ZIP",
  at_sem_docs:        "Nenhum documento anexado",
  at_baixar:          "Baixar",
  at_status_op:       "Operacional",
  at_status_manut:    "Em Manutencao",
  at_status_par:      "Parado",
  // Analise de falha
  at_anal_titulo:     "Analise de Falha",
  at_anal_sem:        "Manutencao corretiva sem analise de falha",
  at_anal_add:        "+ Analise de Falha",
  at_anal_editar:     "editar",
  at_anal_salvar:     "Salvar Analise",
  at_anal_tipos: {
    "5porques": "5 Porques",
    "ishikawa":  "Ishikawa (6M)",
    "fmea":      "FMEA",
    "rca":       "RCA",
    "fta":       "Arvore de Falhas",
    "pdca":      "PDCA"
  },

  // Cadastros
  cad_titulo:         "Cadastros",
  cad_tab_usuarios:   "Usuarios",
  cad_tab_categorias: "Categorias",
  cad_tab_empresas:   "Empresas",
  cad_novo_user:      "+ Novo Usuario",
  cad_nova_cat:       "+ Nova Categoria",
  cad_nova_emp:       "+ Nova Empresa",
  cad_add_unid:       "+ Adicionar Unidade",
  cad_ativos_label:   " ativo(s)",
  cad_unidades_label: " unidade(s)",
  cad_inativar:       "Inativar",
  cad_ativar:         "Ativar",
  cad_excluir:        "Excluir",
  cad_nenhuma_emp:    "Nenhuma empresa cadastrada",
  cad_perfis: {
    Coordenador: "Coordenador",
    Tecnico:     "Tecnico",
    Visualizador:"Visualizador"
  },
  cad_f_nome:         "Nome completo *",
  cad_f_email:        "E-mail *",
  cad_f_telefone:     "Telefone",
  cad_f_senha:        "Senha",
  cad_f_perfil:       "Perfil",
  cad_f_status:       "Status",
  cad_f_ativo:        "✓ Ativo",
  cad_f_inativo:      "✕ Inativo",
  cad_f_cat_nome:     "Nome da Categoria *",
  cad_f_cat_desc:     "Descricao",
  cad_f_cat_icone:    "Icone",
  cad_f_cat_cor:      "Cor",
  cad_f_cat_prev:     "Preview",
  cad_f_emp_nome:     "Razao Social / Nome *",
  cad_f_emp_cnpj:     "CNPJ",
  cad_f_emp_tel:      "Telefone",
  cad_f_emp_end:      "Endereco",
  cad_f_emp_cont:     "Contato responsavel",
  cad_f_unid_nome:    "Nome da Unidade *",
  cad_f_unid_end:     "Endereco / Localizacao",
  cad_f_unid_resp:    "Responsavel",

  // Form campos ativos
  at_f_nome:          "Nome *",
  at_f_cat:           "Categoria",
  at_f_empresa:       "Empresa",
  at_f_unidade:       "Unidade",
  at_f_local:         "Localizacao",
  at_f_fab:           "Fabricante",
  at_f_modelo:        "Modelo",
  at_f_serie:         "Serie",
  at_f_ano:           "Ano",
  at_f_tag:           "Tag",
  at_f_pat:           "Patrimonio",

  // Histórico form
  h_f_desc:           "Descricao *",
  h_f_data:           "Data",
  h_f_tipo:           "Tipo",
  h_f_tecnico:        "Tecnico",
  h_f_horas:          "Horas",
  h_f_custo:          "Custo (R$)",
  h_f_prox:           "Proximo (dias)",
  h_f_obs:            "Observacoes",

  // Plano form
  pl_f_nome:          "Nome *",
  pl_f_freq:          "Frequencia",
  pl_f_prox:          "Proxima Execucao",
  pl_f_resp:          "Responsavel",
  pl_freq: {
    Semanal:"Semanal", Quinzenal:"Quinzenal", Mensal:"Mensal",
    Bimestral:"Bimestral", Trimestral:"Trimestral",
    Semestral:"Semestral", Anual:"Anual"
  },

  // Plano status
  pl_ok:              "OK",
  pl_atrasado:        "Atrasado",
  pl_vence:           "Vence Hoje",
  pl_todos_ok:        "✓ Todos os planos em dia",
  pl_nenhuma_os:      "Nenhuma OS cadastrada",

  // Indicadores
  ind_names: {
    mtbf:"Tempo Medio entre Falhas", mttr:"Tempo Medio de Reparo",
    disp:"Disponibilidade", conf:"Confiabilidade 1000h",
    lambda:"Taxa de Falhas", manuplan:"Manutencao Planejada",
    backlog:"Backlog de OS", nfalhas:"Numero de Falhas",
    compliance:"Compliance Preventivo", mttf:"Tempo Medio ate Falha",
    downtime:"Horas Indisponivel", oee_a:"Disponibilidade OEE"
  },
  ind_abbrs: {
    mtbf:"MTBF", mttr:"MTTR", disp:"A(%)", conf:"R(t)",
    lambda:"Txa-F", manuplan:"MP%", backlog:"BKL",
    nfalhas:"NF", compliance:"CP%", mttf:"MTTF",
    downtime:"DT", oee_a:"OEE-A"
  },

  // Botões comuns
  btn_salvar:    "Salvar",
  btn_cancelar:  "Cancelar",
  btn_editar:    "Editar",
  btn_excluir:   "Excluir",
  btn_voltar:    "← Voltar",
  btn_novo:      "+ Novo",
  btn_cadastrar: "Cadastrar",
  btn_criar_os:  "Criar OS",
  btn_selecione: "Selecione...",
  btn_sel_emp:   "Selecione a empresa...",
  btn_sel_unid:  "Selecione a unidade...",
  btn_sem_emp:   "Nenhuma empresa cadastrada",

  // ── NAV / COMUM (novo) ──────────────────────────────────────────────────
  nav_calendario:  "Calendario",
  nav_relatorios:  "Relatorios",
  nav_recolher:    "Recolher",
  nav_cal_short:   "Cal.",
  nav_rel_short:   "Rel.",
  btn_sair:        "Sair",
  msg_sair:        "Sair do Mantenedor?",
  msg_sem_permissao: "Essa area e restrita ao perfil Coordenador.",
  msg_erro_empresa:  "Erro ao salvar dados da empresa: ",
  msg_sem_empresa:   "Nao foi possivel salvar: sessao sem empresa associada. Faca login novamente.",

  // Titulos de pagina (<title> e topbar)
  title_dashboard:     "Dashboard",
  title_ordens:        "Ordens de Servico",
  title_ativos:        "Gestao de Ativos",
  title_cadastros:     "Cadastros",
  title_calendario:    "Calendario",
  title_relatorios:    "Relatorios",
  title_os_corretiva:  "OS Corretiva",
  title_os_programada: "OS Preventiva / Preditiva",
  title_login:         "Entrar",

  // ── CALENDARIO ──────────────────────────────────────────────────────────
  cal_mes:         "Mes",
  cal_semana:      "Semana",
  cal_hoje:        "Hoje",
  cal_sem_eventos: "Sem eventos",
  cal_os_mes: "OS no Mes",
  cal_planos: "Planos",
  cal_criticas: "Criticas",
  cal_atrasados: "Atrasados",
  cal_os_plano: "OS Plano",
  cal_plano: "Plano",
  cal_plano_suf: " — Plano",
  cal_meses:       ["Janeiro","Fevereiro","Marco","Abril","Maio","Junho",
                    "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],
  cal_meses_short: ["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"],
  cal_dias:        ["Dom","Seg","Ter","Qua","Qui","Sex","Sab"],

  // ── RELATORIOS ──────────────────────────────────────────────────────────
  rel_titulo:       "Relatorios",
  rel_tipo_os:      "OS Realizadas",
  rel_tipo_hist:    "Historico de Ativos",
  rel_filtros:      "Filtros",
  rel_limpar:       "Limpar filtros",
  rel_imprimir:     "Imprimir / PDF",
  rel_todos:        "Todos",
  rel_status:       "Status",
  rel_prazo:        "Prazo",
  rel_abertura:     "Abertura",
  rel_prioridade:   "Prioridade",
  rel_tecnico:      "Tecnico Responsavel",
  rel_de:           "De:",
  rel_ate:          "Ate: ",
  rel_ativo:        "Ativo: ",
  rel_status_lbl:   "Status: ",
  rel_empresa:      "Empresa (terceirizada/cliente)",
  rel_unidade:      "Unidade",
  rel_unidade_lbl:  "Unidade:",
  rel_buscar_os:    "Buscar OS por numero",
  rel_num_exemplo:  "Ex.: 2026-COR-0004",
  rel_informe_num:  "Informe o numero da OS.",
  rel_nao_encontrada: "Nenhuma OS encontrada com o numero ",
  rel_concluidas:   "Concluidas",
  rel_em_aberto:    "Em aberto",
  rel_criticas:     "Criticas",
  rel_custo_total:  "Custo total",
  rel_horas_total:  "Horas total",
  rel_registros:    "Registros",
  rel_analise:      "Analise",
  rel_com_analise:  "Com analise de falha",
  rel_sem_analise:  "Sem analise de falha",
  rel_com_e_sem:    "Com e sem analise",
  rel_sim:          "Sim",
  rel_nao:          "Nao",
  rel_gerado_em:    "Gerado em ",
  rel_cnpj:         "CNPJ ",
  rel_cliente: "Cliente:",
  rel_endereco: "Endereco:",
  rel_tipo_lbl: "Tipo: ",
  rel_filtros_apl: "Filtros aplicados: ",
  rel_titulo_os_rel: "Relatorio de Ordens de Servico",
  rel_titulo_hist_rel: "Relatorio de Historico de Manutencao",
  rel_todas_unidades: "Todas as unidades",
  rel_todos_ativos: "Todos os ativos",
  rel_todas_empresas: "Todas as empresas",
  rel_data_inicio: "Data inicio",
  rel_data_fim: "Data fim",
  rel_imprimir_pdf: "Imprimir / Salvar PDF",
  rel_imprimir_os: "Imprimir uma OS especifica (numero)",
  rel_buscar_impr: "Buscar e imprimir",
  rel_total: "Total",
  rel_vazio_os: "Nenhuma OS encontrada com os filtros selecionados.",
  rel_vazio_hist: "Nenhum registro de manutencao encontrado.",
  rel_mista: "Mista",
  rel_dados_gerais: "Dados Gerais",
  rel_desc_servico: "Descricao do Servico Solicitado",
  rel_obs_tec: "Observacoes Tecnicas",
  rel_med_reg: "Medicoes Registradas",
  rel_pecas_mat: "Pecas e Materiais Utilizados",
  rel_reg_foto: "Registros Fotograficos",
  rel_checklist: "Checklist de Planos",
  rel_aceite: "Responsavel do Cliente — Aceite do Servico",
  rel_tec_exec: "Tecnico Executante",
  rel_col_param: "Parametro",
  rel_col_valor: "Valor",
  rel_col_limite: "Limite",
  rel_col_cond: "Condicao",
  rel_col_desc: "Descricao",
  rel_col_qtd: "Qtd",
  rel_col_custo_un: "Custo Unit.",
  rel_col_subtotal: "Subtotal",
  rel_col_data: "Data",
  rel_col_horas: "Horas",
  rel_col_custo: "Custo",
  rel_total_horas: "Total de horas: ",
  rel_total_pecas: "Total em pecas: ",
  an_porque: "Por que ",
  an_causa_raiz: "Causa raiz:",
  an_acao_corr: "Acao corretiva:",
  an_modo_falha: "Modo de falha:",
  an_efeito: "Efeito:",
  an_causa: "Causa:",
  an_npr: "NPR:",
  an_acao: "Acao:",
  an_descricao: "Descricao:",

  // ── CADASTROS (complemento) ─────────────────────────────────────────────
  cad_acesso:        "Acesso ao sistema",
  cad_convite_ger:   "Convite gerado",
  cad_convite_pend:  "Convite pendente",
  cad_copiar_link:   "Copiar link",
  cad_fechar:        "Fechar",
  cad_nova_unid:     "Nova Unidade",
  cad_salvar_emp:    "Salvar dados da empresa",
  cad_coords:        "Coord.",
  cad_tecnicos:      "Tecnicos",
  cad_inativos:      "Inativos",
  cad_sem_desc:      "Sem descricao",
  cad_cats_cad:      " categorias cadastradas",
  cad_emps_cad:      " empresa(s)",
  cad_contato_resp:  "Contato / Responsavel tecnico",
  cad_contato:       "Contato responsavel",
  cad_contato_lbl:   "Contato: ",
  cad_resp_lbl:      "Resp: ",
  cad_razao_social:  "Razao Social / Nome *",
  cad_unid_nome:     "Nome da Unidade *",
  cad_novo_user_tit: "Novo Usuario",
  cad_nova_cat_tit:  "Nova Categoria",
  cad_nova_emp_tit:  "Nova Empresa",

  // ── LOGIN ───────────────────────────────────────────────────────────────
  lg_entrar:        "Entrar",
  lg_criar_conta:   "Criar Conta",
  lg_criar_gratis:  "Criar Conta Gratis",
  lg_email:         "E-mail",
  lg_senha:         "Senha",
  lg_conf_senha:    "Confirme a senha",
  lg_crie_senha:    "Crie uma senha",
  lg_seu_nome:      "Seu Nome",
  lg_empresa:       "Nome da Empresa",
  lg_empresa_hint:  "Sera o nome da sua conta no Mantenedor",
  lg_plano_inclui:  "plano gratuito inclui",
  lg_ativos_ilim:   "✓ Ativos ilimitados",
  lg_os_ilim:       "✓ OS ilimitadas",
  lg_planos_manut:  "✓ Planos de manutencao",
  lg_relatorios:    "✓ Relatorios",
  lg_termos:        "Termos",
  lg_privacidade:   "Privacidade",
  lg_carregando:    "Carregando convite...",
  at_sel_empresa: "Selecione a empresa...",
  at_sel_unidade: "Selecione a unidade...",
  at_cad_ativo: "Cadastrar Ativo",
  at_editar_ativo: "Editar Ativo",
  h_tipo_insp: "Inspecao",
  at_ph_nome: "Nome do equipamento",
  at_ph_local: "Ex: Galpao A, Linha 1",
  at_ph_ano: "Ex: 2020",
  at_ph_tag: "Ex: COMP-002",
  at_ph_pat: "Ex: PAT-0001",
  h_ph_desc: "O que foi feito?",
  pl_novo_titulo: "Novo Plano",
  pl_ph_nome: "Ex: Lubrificacao mensal",
  pl_acoes: "Acoes / Medicoes do Plano",
  pl_add_acao: "+ Acao (checklist)",
  pl_add_med: "+ Medicao",
  pl_salvar: "Salvar Plano",
  pr_nova_titulo: "Nova Leitura Preditiva",
  pr_lim_alerta: "Limite de alerta",
  pr_unidade: "Unidade",
  pr_ph_param: "Ex: Vibracao, Temperatura, Pressao...",
  pr_ph_unidade: "Ex: mm/s, C, bar...",
  pr_ph_obs: "Condicao observada...",
  pr_params: {vib:"Vibracao (mm/s)", temp:"Temperatura (C)", ruido:"Ruido (dB)", pres:"Pressao (bar)", corr:"Corrente (A)", esp:"Espessura (mm)", outro:"Outro"},
  an_titulo: "Analise de Falha",
  an_problema: "Problema observado",
  an_ph_problema: "Descreva a falha observada...",
  an_causa_raiz_l: "Causa Raiz",
  an_ph_causa_pq: "Resposta final — causa fundamental...",
  an_acao_corr_l: "Acao Corretiva",
  an_salvar: "Salvar Analise",
  an_5pq_hint: "Questione \"por que?\" sucessivamente ate chegar a causa raiz.",
  an_ish_hint: "Diagrama Espinha de Peixe: identifique causas nos 6M.",
  an_ish_efeito: "Efeito / Falha Central",
  an_ish_ph_ef: "Ex: Parada nao planejada do equipamento",
  an_6m_mo: "Mao de Obra",
  an_6m_maq: "Maquina",
  an_6m_met: "Metodo",
  an_6m_mat: "Material",
  an_6m_amb: "Meio Ambiente",
  an_6m_med: "Medicao",
  an_6m_ph_mo: "Erro operacional, treinamento...",
  an_6m_ph_maq: "Desgaste, falta de manutencao...",
  an_6m_ph_met: "Procedimento, padrao...",
  an_6m_ph_mat: "Qualidade, especificacao...",
  an_6m_ph_amb: "Temperatura, umidade...",
  an_6m_ph_med: "Instrumento, monitoramento...",
  an_ish_causa: "Causa Raiz Predominante",
  an_ish_ph_causa: "Qual dos 6M foi a causa principal?",
  an_fmea_modo: "Modo de Falha",
  an_fmea_ph_modo: "Ex: Ruptura de rolamento",
  an_fmea_efeito: "Efeito",
  an_fmea_ph_ef: "Ex: Parada do equipamento",
  an_fmea_causa: "Causa",
  an_fmea_ph_causa: "Ex: Lubrificacao insuficiente",
  an_fmea_ctrl: "Controle Atual",
  an_fmea_ph_ctrl: "Ex: Inspecao visual mensal",
  an_fmea_sev: "Severidade (S) 1-10",
  an_fmea_ocor: "Ocorrencia (O) 1-10",
  an_fmea_det: "Deteccao (D) 1-10",
  an_fmea_sem_ef: "Sem efeito",
  an_fmea_catast: "Catastrofico",
  an_fmea_improv: "Improvavel",
  an_fmea_certo: "Certo",
  an_fmea_detect: "Detectavel",
  an_fmea_indet: "Indetectavel",
  an_fmea_rpn: "RPN = S × O × D",
  an_fmea_acao_rec: "Acao Recomendada",
  an_fmea_resp: "Responsavel / Prazo",
  an_fmea_ph_resp: "Ex: Joao Silva — ate 30/06/2026",
  an_rca_hint: "Root Cause Analysis: cadeia de eventos que levou a falha.",
  an_rca_decl: "Declaracao do Problema",
  an_rca_ph_decl: "O que falhou, quando, como e com que frequencia...",
  an_rca_time: "Linha do Tempo",
  an_rca_ph_time: "14h00 — operador notou ruido\n15h00 — parada de emergencia...",
  an_rca_fat: "Fatores Contribuintes",
  an_rca_ph_fat: "Fatores humanos, tecnicos, organizacionais...",
  an_rca_ph_causa: "A causa fundamental...",
  an_rca_acoes: "Acoes Corretivas",
  an_rca_verif: "Verificacao da Eficacia",
  an_rca_ph_verif: "Como e quando verificar?",
  an_fta_topo: "Evento Topo",
  an_fta_ph_topo: "Ex: Parada nao planejada",
  an_fta_diretas: "Causas Diretas",
  an_fta_basicas: "Causas Basicas (raiz)",
  an_fta_add: "+ Adicionar",
  an_fta_porta: "Porta Logica",
  an_fta_and: "AND — todas as causas juntas",
  an_fta_or: "OR — qualquer causa e suficiente",
  an_fta_acao: "Acao Preventiva",
  an_pdca_hint: "Ciclo PDCA para resolucao e melhoria continua.",
  an_pdca_p: "P — Planejar",
  an_pdca_d: "D — Executar",
  an_pdca_c: "C — Verificar",
  an_pdca_a: "A — Agir",
  an_pdca_ph_p: "Qual o problema? Meta? O que fazer?",
  an_pdca_ph_d: "Quem? Quando? Como?",
  an_pdca_ph_c: "Como medir o resultado?",
  an_pdca_ph_a: "O que padronizar? Ajustar?",
  an_fmea_hint: "RPN = Severidade × Ocorrencia × Deteccao. Acima de 100 exige acao imediata.",
  an_fta_hint: "Arvore de Falhas: partindo do evento topo, identifique causas por portas logicas.",
  enum_labels: {
    "Aberta":"Aberta",
    "Em Andamento":"Em Andamento",
    "Concluida":"Concluida",
    "Cancelada":"Cancelada",
    "Critica":"Critica",
    "Alta":"Alta",
    "Normal":"Normal",
    "Baixa":"Baixa",
    "Corretiva":"Corretiva",
    "Preventiva":"Preventiva",
    "Preditiva":"Preditiva",
    "Mista":"Mista",
    "Inspecao":"Inspecao",
    "Operacional":"Operacional",
    "Em Manutencao":"Em Manutencao",
    "Parado":"Parado",
    "Desativado":"Desativado",
    "OK":"OK",
    "Atrasado":"Atrasado",
    "Vence Hoje":"Vence Hoje",
    "Vence em Breve":"Vence em Breve",
    "Ambos":"Ambos"
  },
  crit_alto_plano: "ALTO — Plano necessario",
  crit_baixo_aceit: "BAIXO — Aceitavel",
  crit_critico_imed: "CRITICO — Acao imediata",
  crit_medio_monit: "MEDIO — Monitorar",
  an_lbl_acao: "Acao:",
  an_lbl_acoes: "Acoes:",
  an_lbl_analise: "Analise:",
  an_lbl_causa_raiz: "Causa raiz:",
  an_lbl_causa: "Causa:",
  an_lbl_efeito: "Efeito:",
  an_lbl_evento_topo: "Evento topo:",
  an_lbl_modo: "Modo:",
  an_lbl_problema: "Problema:",
  at_desativar: "Desativar",
  at_reativar: "Reativar",
  at_desat_titulo: "Desativar Ativo",
  at_justificativa: "Justificativa *",
  at_gerar_os: "Gerar OS",
  at_info_equip: "Informacoes do Equipamento",
  at_nenhum_plano_cad: "Nenhum plano cadastrado",
  cad_ph_desc_breve: "Descricao breve...",
  os_confirmar_concl: "Confirmar conclusao desta OS?",
  os_informe_desc: "Informe a descricao.",
  os_informe_peca: "Informe a peca.",
  os_informe_val_med: "Informe o valor medido.",
  os_sel_imagem: "Selecione uma imagem.",
  os_ativo_invalido: "Ativo invalido.",
  os_preencha_tit: "Preencha titulo e ativo.",
  os_nao_encontrada: "OS nao encontrada para id:",
  os_gerar_prog: "Gerar OS Programadas",
  os_executar: "Executar",
  os_iniciar_exec: "Iniciar Execucao",
  os_acima_max: "Acima do limite maximo!",
  os_abaixo_min: "Abaixo do limite minimo!",
  os_ph_peca: "Ex: Rolamento SKF 6205",
  os_ph_cod_forn: "Codigo, fornecedor...",
  os_ph_contexto: "Contexto ou detalhe...",
  os_ph_foto: "O que a foto mostra...",
  os_ph_obs: "O que foi observado, feito ou encontrado...",
  os_ph_desc_prob: "Descreva o problema ou servico a executar...",
  os_ph_desc_serv: "Descreva o servico a executar...",
  os_ph_desc_res: "Descricao resumida do servico",
  os_ph_30: "Ex: 30",
  msg_so_coord_ativos: "Apenas Coordenadores podem cadastrar ativos.",
  msg_so_coord_planos: "Apenas Coordenadores podem gerenciar planos.",
  msg_so_coord_desat_pl: "Apenas Coordenadores podem desativar planos.",
  msg_so_coord_desat_at: "Apenas Coordenadores podem desativar ativos.",
  msg_so_coord_reat_pl: "Apenas Coordenadores podem reativar planos.",
  msg_so_coord_reat_at: "Apenas Coordenadores podem reativar ativos.",
  msg_so_coord_excl_pl: "Apenas Coordenadores podem excluir planos.",
  msg_informe_nome: "Informe o nome.",
  msg_informe_desc: "Informe a descricao.",
  msg_informe_valor: "Informe o valor.",
  msg_informe_param: "Informe o parametro.",
  msg_informe_justif: "Informe a justificativa para desativar o ativo.",
  msg_reativar_plano: "Reativar este plano?",
  msg_reativar_ativo: "Reativar este ativo?",
  msg_excluir_plano: "Excluir este plano?",
  msg_os_ja_aberta: "Ja existe uma OS em aberto para este plano (OS #",
  msg_sem_plano_venc: "Nenhum plano vencido ou com vencimento em 7 dias.",
  msg_os_geradas: " OS gerada(s) com sucesso!",
  pl_editar_titulo: "Editar Plano",
  pl_ac_desc_med: "Descricao da medicao *",
  pl_ac_desc_acao: "Descricao da acao *",
  pl_ac_param: "Parametro",
  pl_ac_unidade: "Unidade",
  pl_ac_lim_min: "Limite min",
  pl_ac_lim_max: "Limite max",
  an_ph_evento: "Descreva o evento...",
  an_6m_amb_curto: "Meio Amb.",
  at_ph_motivo: "Ex: Equipamento obsoleto, aguardando substituicao...",
  crit_c_hse: "HSE — Seguranca / Saude / Meio Ambiente",
  crit_c_prod: "Producao / Operacao",
  crit_c_custo: "Custo de Reparo / Substituicao",
  crit_c_freq: "Frequencia de Falha (MTBF)",
  crit_c_det: "Detectabilidade da Falha",
  crit_c_red: "Redundancia / Modo de Falha",
  msg_os_canceladas: " OS aberta(s) cancelada(s) por desativacao do ativo.",
  lg_msg_sessao: "Sua sessao expirou ou ficou sem empresa associada. Faca login novamente.",
  lg_msg_convite_nc: "Convite ainda nao carregado.",
  lg_msg_senha_curta: "Senha deve ter ao menos 6 caracteres.",
  lg_msg_senha_dif: "As senhas nao coincidem.",
  lg_msg_email_existe: "Este e-mail ja tem uma conta cadastrada. Tente fazer login normalmente com a senha que voce ja usa, ou peca ao coordenador para apagar o usuario duplicado antes de gerar um novo convite.",
  lg_msg_confirme: "Conta criada. Confirme seu e-mail e depois faca login normalmente.",
  lg_msg_vinc_falha: "Nao foi possivel vincular o convite. Tente novamente.",
  lg_msg_criada: "Conta criada! Redirecionando...",
  lg_msg_vinc_erro: "Erro ao vincular o convite. Sua conta foi criada — tente fazer login normalmente.",
  lg_msg_conexao: "Erro de conexao. Tente novamente.",
  lg_msg_preencha: "Preencha e-mail e senha.",
  lg_msg_incorretos: "E-mail ou senha incorretos.",
  lg_msg_sem_conta: "Conta nao encontrada. Crie uma conta.",
  lg_msg_carregar: "Erro ao carregar dados. Tente novamente.",
  lg_msg_todos: "Preencha todos os campos.",
  lg_ph_email: "seu@email.com",
  lg_ph_nome: "Nome completo",
  lg_ph_empresa: "Ex: Metalurgica Sao Paulo",
  lg_ph_min6: "Minimo 6 caracteres",
  lg_ph_repita: "Repita a senha",
},

// ── ENGLISH ────────────────────────────────────────────────────────────────
en: {
  nav_dashboard:    "Dashboard",
  nav_ordens:       "Work Orders",
  nav_ativos:       "Asset Management",
  nav_cadastros:    "Settings",
  nav_os:           "WO",
  nav_ativos_short: "Assets",

  topbar_alert_criticas: " critical WO(s) open",

  dash_status:      "Operational Status",
  dash_confiab:     "Reliability & Availability",
  dash_gestao:      "Maintenance Management",
  dash_criticidade: "Asset Criticality (NORSOK Z-008 / API RP 581)",
  dash_ultimas_os:  "Latest Work Orders",
  dash_equipamentos:"Equipment",
  dash_planos:      "Attention Required",
  dash_ver_todas:   "View all →",
  dash_calcular:    "Calculate in asset sheet →",
  dash_planos_ok:   "✓ All plans on schedule",

  kpi_abertas:      "Open WOs",
  kpi_andamento:    "In Progress",
  kpi_criticas:     "Critical WOs",
  kpi_equipamentos: "Equipment",
  kpi_mtbf:         "Global MTBF",
  kpi_mttr:         "Global MTTR",
  kpi_disponib:     "Avail.",
  kpi_manuplan:     "Planned Maint.",
  kpi_compliance:   "Compliance",
  kpi_backlog:      "Backlog",
  kpi_falhas:       "Corrective Fail.",
  kpi_aguardando:   "waiting",
  kpi_em_exec:      "in progress",
  kpi_prio_max:     "max priority",
  kpi_operando:     "running",

  crit_matriz:      "Risk Matrix (Consequence x Probability)",
  crit_ativos:      "Assets by Criticality",
  crit_eixo_y:      "Y-Axis: Consequence",
  crit_eixo_x:      "X-Axis: Probability",
  crit_score:       "Criticality Score (0-100)",
  crit_warn_super:  "% of assets classified as Critical — above 30% limit (NORSOK Z-008). Recalibrate criteria.",
  crit_ok_bench:    "✓ Distribution within benchmark (5-15% critical) — NORSOK Z-008",
  crit_vazio:       'Open each asset sheet and calculate criticality in the "Criticality" tab.',
  crit_mais:        "+more ",
  crit_avaliados:   " assets evaluated",
  crit_classes:     {A:"Critical", B:"High", C:"Medium", D:"Low"},
  crit_recs: {
    A: "Continuous monitoring (predictive). Mandatory contingency plan. FMEA and root cause analysis.",
    B: "Systematic preventive maintenance. Condition monitoring recommended. Include in inspection plan.",
    C: "Time/cycle-based preventive maintenance. Evaluate predictive cost-benefit.",
    D: "Planned corrective maintenance acceptable (run-to-failure). Ensure spare parts available."
  },

  ord_titulo:       "Work Orders",
  ord_nova:         "+ New WO",
  ord_filtro_todas: "All",
  ord_tipo_label:   "Maintenance Type",
  ord_tipo_corr:    "Corrective",
  ord_tipo_prev:    "Preventive",
  ord_tipo_pred:    "Predictive",
  ord_prio_label:   "Priority",
  ord_prio_crit:    "Critical",
  ord_prio_alta:    "High",
  ord_prio_normal:  "Normal",
  ord_prio_baixa:   "Low",
  ord_status_aberta:"Open",
  ord_status_and:   "In Progress",
  ord_status_conc:  "Completed",
  ord_status_canc:  "Cancelled",
  ord_iniciar:      "▶ Start Execution",
  ord_registrar:    "+ Log Activity",
  ord_concluir:     "✓ Complete WO",
  ord_cancelar:     "✕ Cancel",
  ord_finalizada:   "WO closed",
  ord_sem_prazo:    "No deadline",
  ord_atribuida_a:  "WO assigned to",
  ord_periodo:      "Period",
  ord_proxima_em:   "Next WO in",
  ord_reg_exec:     "Execution Log",
  ord_sem_reg:      "No records yet",
  ord_inicia_para_reg: "Start WO to begin logging",
  ord_total_pecas:  "in parts",
  ord_nenhuma:      "No work orders found",
  ord_nenhuma_cad:  "No work orders registered",
  ord_f_titulo:     "Title *",
  ord_f_ativo:      "Asset *",
  ord_f_tipo:       "Type",
  ord_f_prio:       "Priority",
  ord_f_tecnico:    "Assigned Technician",
  ord_f_prazo:      "Deadline",
  ord_f_periodo:    "Period (days)",
  ord_f_proxima:    "Next WO in (days)",
  ord_f_descricao:  "Description / Symptom",
  ord_f_ativo_label:"Asset",
  ord_f_abertura:   "Opened",
  ord_f_tipo2:      "Type",
  exec_tipo_obs:    "Observation",
  exec_tipo_med:    "Measurement",
  exec_tipo_peca:   "Part / Material",
  exec_tipo_foto:   "Photo",
  exec_param:       "Measured parameter",
  exec_valor:       "Measured value *",
  exec_limite:      "Limit / Reference",
  exec_cond:        "Condition",
  exec_cond_normal: "Normal",
  exec_cond_atenc:  "Warning",
  exec_cond_crit:   "Critical",
  exec_cond_fora:   "Out of spec",
  exec_peca_desc:   "Part / Material description *",
  exec_qty:         "Quantity",
  exec_custo:       "Unit cost ($)",
  exec_foto_desc:   "Photo description",
  exec_ultimo_reg:  "Last entry",
  exec_qtd_reg:     " records",

  at_titulo:        "Asset Management",
  at_ficha:         "Sheet: ",
  at_novo:          "+ New Asset",
  at_clique:        "Tap an asset to open its full sheet",
  at_nenhum:        "No assets registered",
  at_tabs: {
    geral:"General", indicadores:"Indicators", historico:"History",
    preventiva:"Maint. Plan", preditiva:"Measurements",
    documentos:"Documents", criticidade:"Criticality"
  },
  at_info_fabricante:"Manufacturer",
  at_info_modelo:    "Model",
  at_info_serie:     "Serial No.",
  at_info_ano:       "Year",
  at_info_local:     "Location",
  at_info_cat:       "Category",
  at_info_tag:       "Tag",
  at_info_pat:       "Asset No.",
  at_info_empresa:   "Company",
  at_info_unidade:   "Unit",
  at_resumo:         "Summary & Last Intervention",
  at_intervencoes:   "Interventions",
  at_corretivas:     "Corrective",
  at_horas:          "Maint. Hours",
  at_ultima_int:     "Last Intervention",
  at_sem_hist:       "No maintenance records",
  at_sel_ind:        "Select Indicators",
  at_sel_ind_sub:    "Click to enable or disable each indicator for this asset.",
  at_nenhum_ind:     "No indicators enabled. Select below.",
  at_reg_manut:      "+ Log Maintenance",
  at_registros:      " record(s)",
  at_sem_manut:      "No maintenance logged yet.",
  at_novo_plano:     "+ New Plan",
  at_nenhum_plano:   "No preventive plans registered",
  at_planos_atraso:  " plan(s) require attention",
  at_nova_leitura:   "+ New Reading",
  at_sem_leituras:   "No predictive readings registered.",
  at_mais_leituras:  "Add more readings to generate chart",
  at_acima_limite:   "Last value above alert limit!",
  at_valor_med:      "Measured value",
  at_limite:         "Limit",
  at_anexar:         "Click to attach documents",
  at_anexar_sub:     "PDF, Word, Excel, Images, ZIP",
  at_sem_docs:       "No documents attached",
  at_baixar:         "Download",
  at_status_op:      "Operational",
  at_status_manut:   "Under Maintenance",
  at_status_par:     "Stopped",
  at_anal_titulo:    "Failure Analysis",
  at_anal_sem:       "Corrective maintenance without failure analysis",
  at_anal_add:       "+ Failure Analysis",
  at_anal_editar:    "edit",
  at_anal_salvar:    "Save Analysis",
  at_anal_tipos: {
    "5porques":"5 Whys", "ishikawa":"Ishikawa (6M)",
    "fmea":"FMEA", "rca":"RCA",
    "fta":"Fault Tree", "pdca":"PDCA"
  },

  cad_titulo:         "Settings",
  cad_tab_usuarios:   "Users",
  cad_tab_categorias: "Categories",
  cad_tab_empresas:   "Companies",
  cad_novo_user:      "+ New User",
  cad_nova_cat:       "+ New Category",
  cad_nova_emp:       "+ New Company",
  cad_add_unid:       "+ Add Unit",
  cad_ativos_label:   " asset(s)",
  cad_unidades_label: " unit(s)",
  cad_inativar:       "Deactivate",
  cad_ativar:         "Activate",
  cad_excluir:        "Delete",
  cad_nenhuma_emp:    "No companies registered",
  cad_perfis: {Coordenador:"Coordinator", Tecnico:"Technician", Visualizador:"Viewer"},
  cad_f_nome:         "Full name *",
  cad_f_email:        "E-mail *",
  cad_f_telefone:     "Phone",
  cad_f_senha:        "Password",
  cad_f_perfil:       "Role",
  cad_f_status:       "Status",
  cad_f_ativo:        "✓ Active",
  cad_f_inativo:      "✕ Inactive",
  cad_f_cat_nome:     "Category name *",
  cad_f_cat_desc:     "Description",
  cad_f_cat_icone:    "Icon",
  cad_f_cat_cor:      "Color",
  cad_f_cat_prev:     "Preview",
  cad_f_emp_nome:     "Company name *",
  cad_f_emp_cnpj:     "Tax ID",
  cad_f_emp_tel:      "Phone",
  cad_f_emp_end:      "Address",
  cad_f_emp_cont:     "Contact person",
  cad_f_unid_nome:    "Unit name *",
  cad_f_unid_end:     "Address / Location",
  cad_f_unid_resp:    "Responsible",

  at_f_nome:"Name *", at_f_cat:"Category", at_f_empresa:"Company",
  at_f_unidade:"Unit", at_f_local:"Location", at_f_fab:"Manufacturer",
  at_f_modelo:"Model", at_f_serie:"Serial No.", at_f_ano:"Year",
  at_f_tag:"Tag", at_f_pat:"Asset No.",

  h_f_desc:"Description *", h_f_data:"Date", h_f_tipo:"Type",
  h_f_tecnico:"Technician", h_f_horas:"Hours", h_f_custo:"Cost ($)",
  h_f_prox:"Next (days)", h_f_obs:"Notes",

  pl_f_nome:"Name *", pl_f_freq:"Frequency",
  pl_f_prox:"Next Execution", pl_f_resp:"Responsible",
  pl_freq: {
    Semanal:"Weekly", Quinzenal:"Biweekly", Mensal:"Monthly",
    Bimestral:"Bimonthly", Trimestral:"Quarterly",
    Semestral:"Semiannual", Anual:"Annual"
  },
  pl_ok:"OK", pl_atrasado:"Overdue", pl_vence:"Due Today",
  pl_todos_ok:"✓ All plans on schedule",
  pl_nenhuma_os:"No work orders registered",

  ind_names: {
    mtbf:"Mean Time Between Failures", mttr:"Mean Time To Repair",
    disp:"Availability", conf:"Reliability 1000h",
    lambda:"Failure Rate", manuplan:"Planned Maintenance",
    backlog:"WO Backlog", nfalhas:"Failure Count",
    compliance:"Preventive Compliance", mttf:"Mean Time To Failure",
    downtime:"Downtime Hours", oee_a:"OEE Availability"
  },
  ind_abbrs: {
    mtbf:"MTBF", mttr:"MTTR", disp:"A(%)", conf:"R(t)",
    lambda:"F-Rate", manuplan:"PM%", backlog:"BKL",
    nfalhas:"FC", compliance:"PC%", mttf:"MTTF",
    downtime:"DT", oee_a:"OEE-A"
  },

  btn_salvar:"Save", btn_cancelar:"Cancel", btn_editar:"Edit",
  btn_excluir:"Delete", btn_voltar:"← Back", btn_novo:"+ New",
  btn_cadastrar:"Register", btn_criar_os:"Create WO",
  btn_selecione:"Select...", btn_sel_emp:"Select company...",
  btn_sel_unid:"Select unit...", btn_sem_emp:"No companies registered",

  // ── NAV / COMMON (new) ──────────────────────────────────────────────────
  nav_calendario:  "Calendar",
  nav_relatorios:  "Reports",
  nav_recolher:    "Collapse",
  nav_cal_short:   "Cal.",
  nav_rel_short:   "Rep.",
  btn_sair:        "Log out",
  msg_sair:        "Log out of Mantenedor?",
  msg_sem_permissao: "This area is restricted to the Coordinator role.",
  msg_erro_empresa:  "Error saving company data: ",
  msg_sem_empresa:   "Could not save: session has no company associated. Please log in again.",

  title_dashboard:     "Dashboard",
  title_ordens:        "Work Orders",
  title_ativos:        "Asset Management",
  title_cadastros:     "Settings",
  title_calendario:    "Calendar",
  title_relatorios:    "Reports",
  title_os_corretiva:  "Corrective WO",
  title_os_programada: "Preventive / Predictive WO",
  title_login:         "Sign in",

  // ── CALENDAR ────────────────────────────────────────────────────────────
  cal_mes:         "Month",
  cal_semana:      "Week",
  cal_hoje:        "Today",
  cal_sem_eventos: "No events",
  cal_os_mes: "WOs this Month",
  cal_planos: "Plans",
  cal_criticas: "Critical",
  cal_atrasados: "Overdue",
  cal_os_plano: "Plan WO",
  cal_plano: "Plan",
  cal_plano_suf: " — Plan",
  cal_meses:       ["January","February","March","April","May","June",
                    "July","August","September","October","November","December"],
  cal_meses_short: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
  cal_dias:        ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],

  // ── REPORTS ─────────────────────────────────────────────────────────────
  rel_titulo:       "Reports",
  rel_tipo_os:      "Completed WOs",
  rel_tipo_hist:    "Asset History",
  rel_filtros:      "Filters",
  rel_limpar:       "Clear filters",
  rel_imprimir:     "Print / PDF",
  rel_todos:        "All",
  rel_status:       "Status",
  rel_prazo:        "Deadline",
  rel_abertura:     "Opened",
  rel_prioridade:   "Priority",
  rel_tecnico:      "Assigned Technician",
  rel_de:           "From:",
  rel_ate:          "To: ",
  rel_ativo:        "Asset: ",
  rel_status_lbl:   "Status: ",
  rel_empresa:      "Company (contractor/client)",
  rel_unidade:      "Unit",
  rel_unidade_lbl:  "Unit:",
  rel_buscar_os:    "Search WO by number",
  rel_num_exemplo:  "e.g. 2026-COR-0004",
  rel_informe_num:  "Enter the WO number.",
  rel_nao_encontrada: "No work order found with number ",
  rel_concluidas:   "Completed",
  rel_em_aberto:    "Open",
  rel_criticas:     "Critical",
  rel_custo_total:  "Total cost",
  rel_horas_total:  "Total hours",
  rel_registros:    "Records",
  rel_analise:      "Analysis",
  rel_com_analise:  "With failure analysis",
  rel_sem_analise:  "Without failure analysis",
  rel_com_e_sem:    "With and without analysis",
  rel_sim:          "Yes",
  rel_nao:          "No",
  rel_gerado_em:    "Generated on ",
  rel_cnpj:         "Tax ID ",
  rel_cliente: "Client:",
  rel_endereco: "Address:",
  rel_tipo_lbl: "Type: ",
  rel_filtros_apl: "Applied filters: ",
  rel_titulo_os_rel: "Work Order Report",
  rel_titulo_hist_rel: "Maintenance History Report",
  rel_todas_unidades: "All units",
  rel_todos_ativos: "All assets",
  rel_todas_empresas: "All companies",
  rel_data_inicio: "Start date",
  rel_data_fim: "End date",
  rel_imprimir_pdf: "Print / Save PDF",
  rel_imprimir_os: "Print a specific WO (number)",
  rel_buscar_impr: "Search and print",
  rel_total: "Total",
  rel_vazio_os: "No work orders found with the selected filters.",
  rel_vazio_hist: "No maintenance records found.",
  rel_mista: "Mixed",
  rel_dados_gerais: "General Data",
  rel_desc_servico: "Requested Service Description",
  rel_obs_tec: "Technical Notes",
  rel_med_reg: "Recorded Measurements",
  rel_pecas_mat: "Parts and Materials Used",
  rel_reg_foto: "Photographic Records",
  rel_checklist: "Plan Checklist",
  rel_aceite: "Client Representative — Service Acceptance",
  rel_tec_exec: "Performing Technician",
  rel_col_param: "Parameter",
  rel_col_valor: "Value",
  rel_col_limite: "Limit",
  rel_col_cond: "Condition",
  rel_col_desc: "Description",
  rel_col_qtd: "Qty",
  rel_col_custo_un: "Unit Cost",
  rel_col_subtotal: "Subtotal",
  rel_col_data: "Date",
  rel_col_horas: "Hours",
  rel_col_custo: "Cost",
  rel_total_horas: "Total hours: ",
  rel_total_pecas: "Total in parts: ",
  an_porque: "Why ",
  an_causa_raiz: "Root cause:",
  an_acao_corr: "Corrective action:",
  an_modo_falha: "Failure mode:",
  an_efeito: "Effect:",
  an_causa: "Cause:",
  an_npr: "RPN:",
  an_acao: "Action:",
  an_descricao: "Description:",

  // ── SETTINGS (complement) ───────────────────────────────────────────────
  cad_acesso:        "System access",
  cad_convite_ger:   "Invite generated",
  cad_convite_pend:  "Invite pending",
  cad_copiar_link:   "Copy link",
  cad_fechar:        "Close",
  cad_nova_unid:     "New Unit",
  cad_salvar_emp:    "Save company data",
  cad_coords:        "Coord.",
  cad_tecnicos:      "Technicians",
  cad_inativos:      "Inactive",
  cad_sem_desc:      "No description",
  cad_cats_cad:      " categories registered",
  cad_emps_cad:      " company(ies)",
  cad_contato_resp:  "Contact / Technical lead",
  cad_contato:       "Contact person",
  cad_contato_lbl:   "Contact: ",
  cad_resp_lbl:      "Lead: ",
  cad_razao_social:  "Legal name / Name *",
  cad_unid_nome:     "Unit name *",
  cad_novo_user_tit: "New User",
  cad_nova_cat_tit:  "New Category",
  cad_nova_emp_tit:  "New Company",

  // ── LOGIN ───────────────────────────────────────────────────────────────
  lg_entrar:        "Sign in",
  lg_criar_conta:   "Create Account",
  lg_criar_gratis:  "Create Free Account",
  lg_email:         "E-mail",
  lg_senha:         "Password",
  lg_conf_senha:    "Confirm password",
  lg_crie_senha:    "Create a password",
  lg_seu_nome:      "Your Name",
  lg_empresa:       "Company Name",
  lg_empresa_hint:  "This will be your account name in Mantenedor",
  lg_plano_inclui:  "free plan includes",
  lg_ativos_ilim:   "✓ Unlimited assets",
  lg_os_ilim:       "✓ Unlimited work orders",
  lg_planos_manut:  "✓ Maintenance plans",
  lg_relatorios:    "✓ Reports",
  lg_termos:        "Terms",
  lg_privacidade:   "Privacy",
  lg_carregando:    "Loading invite...",
  at_sel_empresa: "Select company...",
  at_sel_unidade: "Select unit...",
  at_cad_ativo: "Register Asset",
  at_editar_ativo: "Edit Asset",
  h_tipo_insp: "Inspection",
  at_ph_nome: "Equipment name",
  at_ph_local: "e.g. Building A, Line 1",
  at_ph_ano: "e.g. 2020",
  at_ph_tag: "e.g. COMP-002",
  at_ph_pat: "e.g. PAT-0001",
  h_ph_desc: "What was done?",
  pl_novo_titulo: "New Plan",
  pl_ph_nome: "e.g. Monthly lubrication",
  pl_acoes: "Plan Actions / Measurements",
  pl_add_acao: "+ Action (checklist)",
  pl_add_med: "+ Measurement",
  pl_salvar: "Save Plan",
  pr_nova_titulo: "New Predictive Reading",
  pr_lim_alerta: "Alert limit",
  pr_unidade: "Unit",
  pr_ph_param: "E.g. Vibration, Temperature, Pressure...",
  pr_ph_unidade: "E.g. mm/s, C, bar...",
  pr_ph_obs: "Observed condition...",
  pr_params: {vib:"Vibration (mm/s)", temp:"Temperature (C)", ruido:"Noise (dB)", pres:"Pressure (bar)", corr:"Current (A)", esp:"Thickness (mm)", outro:"Other"},
  an_titulo: "Failure Analysis",
  an_problema: "Observed problem",
  an_ph_problema: "Describe the observed failure...",
  an_causa_raiz_l: "Root Cause",
  an_ph_causa_pq: "Final answer — fundamental cause...",
  an_acao_corr_l: "Corrective Action",
  an_salvar: "Save Analysis",
  an_5pq_hint: "Ask \"why?\" repeatedly until you reach the root cause.",
  an_ish_hint: "Fishbone Diagram: identify causes across the 6Ms.",
  an_ish_efeito: "Effect / Central Failure",
  an_ish_ph_ef: "e.g. Unplanned equipment shutdown",
  an_6m_mo: "Manpower",
  an_6m_maq: "Machine",
  an_6m_met: "Method",
  an_6m_mat: "Material",
  an_6m_amb: "Environment",
  an_6m_med: "Measurement",
  an_6m_ph_mo: "Operator error, training...",
  an_6m_ph_maq: "Wear, lack of maintenance...",
  an_6m_ph_met: "Procedure, standard...",
  an_6m_ph_mat: "Quality, specification...",
  an_6m_ph_amb: "Temperature, humidity...",
  an_6m_ph_med: "Instrument, monitoring...",
  an_ish_causa: "Predominant Root Cause",
  an_ish_ph_causa: "Which of the 6Ms was the main cause?",
  an_fmea_modo: "Failure Mode",
  an_fmea_ph_modo: "e.g. Bearing failure",
  an_fmea_efeito: "Effect",
  an_fmea_ph_ef: "e.g. Equipment shutdown",
  an_fmea_causa: "Cause",
  an_fmea_ph_causa: "e.g. Insufficient lubrication",
  an_fmea_ctrl: "Current Control",
  an_fmea_ph_ctrl: "e.g. Monthly visual inspection",
  an_fmea_sev: "Severity (S) 1-10",
  an_fmea_ocor: "Occurrence (O) 1-10",
  an_fmea_det: "Detection (D) 1-10",
  an_fmea_sem_ef: "No effect",
  an_fmea_catast: "Catastrophic",
  an_fmea_improv: "Unlikely",
  an_fmea_certo: "Certain",
  an_fmea_detect: "Detectable",
  an_fmea_indet: "Undetectable",
  an_fmea_rpn: "RPN = S × O × D",
  an_fmea_acao_rec: "Recommended Action",
  an_fmea_resp: "Owner / Deadline",
  an_fmea_ph_resp: "e.g. John Smith — by 06/30/2026",
  an_rca_hint: "Root Cause Analysis: chain of events leading to the failure.",
  an_rca_decl: "Problem Statement",
  an_rca_ph_decl: "What failed, when, how and how often...",
  an_rca_time: "Timeline",
  an_rca_ph_time: "2:00pm — operator noticed noise\n3:00pm — emergency shutdown...",
  an_rca_fat: "Contributing Factors",
  an_rca_ph_fat: "Human, technical, organizational factors...",
  an_rca_ph_causa: "The fundamental cause...",
  an_rca_acoes: "Corrective Actions",
  an_rca_verif: "Effectiveness Verification",
  an_rca_ph_verif: "How and when to verify?",
  an_fta_topo: "Top Event",
  an_fta_ph_topo: "e.g. Unplanned shutdown",
  an_fta_diretas: "Direct Causes",
  an_fta_basicas: "Basic Causes (root)",
  an_fta_add: "+ Add",
  an_fta_porta: "Logic Gate",
  an_fta_and: "AND — all causes together",
  an_fta_or: "OR — any cause is sufficient",
  an_fta_acao: "Preventive Action",
  an_pdca_hint: "PDCA cycle for problem solving and continuous improvement.",
  an_pdca_p: "P — Plan",
  an_pdca_d: "D — Do",
  an_pdca_c: "C — Check",
  an_pdca_a: "A — Act",
  an_pdca_ph_p: "What is the problem? Goal? What to do?",
  an_pdca_ph_d: "Who? When? How?",
  an_pdca_ph_c: "How to measure the result?",
  an_pdca_ph_a: "What to standardize? Adjust?",
  an_fmea_hint: "RPN = Severity × Occurrence × Detection. Above 100 requires immediate action.",
  an_fta_hint: "Fault Tree: starting from the top event, identify causes through logic gates.",
  enum_labels: {
    "Aberta":"Open",
    "Em Andamento":"In Progress",
    "Concluida":"Completed",
    "Cancelada":"Cancelled",
    "Critica":"Critical",
    "Alta":"High",
    "Normal":"Normal",
    "Baixa":"Low",
    "Corretiva":"Corrective",
    "Preventiva":"Preventive",
    "Preditiva":"Predictive",
    "Mista":"Mixed",
    "Inspecao":"Inspection",
    "Operacional":"Operational",
    "Em Manutencao":"Under Maintenance",
    "Parado":"Stopped",
    "Desativado":"Deactivated",
    "OK":"OK",
    "Atrasado":"Overdue",
    "Vence Hoje":"Due Today",
    "Vence em Breve":"Due Soon",
    "Ambos":"Both"
  },
  crit_alto_plano: "HIGH — Plan required",
  crit_baixo_aceit: "LOW — Acceptable",
  crit_critico_imed: "CRITICAL — Immediate action",
  crit_medio_monit: "MEDIUM — Monitor",
  an_lbl_acao: "Action:",
  an_lbl_acoes: "Actions:",
  an_lbl_analise: "Analysis:",
  an_lbl_causa_raiz: "Root cause:",
  an_lbl_causa: "Cause:",
  an_lbl_efeito: "Effect:",
  an_lbl_evento_topo: "Top event:",
  an_lbl_modo: "Mode:",
  an_lbl_problema: "Problem:",
  at_desativar: "Deactivate",
  at_reativar: "Reactivate",
  at_desat_titulo: "Deactivate Asset",
  at_justificativa: "Reason *",
  at_gerar_os: "Generate WO",
  at_info_equip: "Equipment Information",
  at_nenhum_plano_cad: "No plans registered",
  cad_ph_desc_breve: "Brief description...",
  os_confirmar_concl: "Confirm completion of this work order?",
  os_informe_desc: "Enter the description.",
  os_informe_peca: "Enter the part.",
  os_informe_val_med: "Enter the measured value.",
  os_sel_imagem: "Select an image.",
  os_ativo_invalido: "Invalid asset.",
  os_preencha_tit: "Fill in title and asset.",
  os_nao_encontrada: "Work order not found for id:",
  os_gerar_prog: "Generate Scheduled WOs",
  os_executar: "Execute",
  os_iniciar_exec: "Start Execution",
  os_acima_max: "Above maximum limit!",
  os_abaixo_min: "Below minimum limit!",
  os_ph_peca: "e.g. SKF 6205 bearing",
  os_ph_cod_forn: "Code, supplier...",
  os_ph_contexto: "Context or detail...",
  os_ph_foto: "What the photo shows...",
  os_ph_obs: "What was observed, done or found...",
  os_ph_desc_prob: "Describe the problem or service to perform...",
  os_ph_desc_serv: "Describe the service to perform...",
  os_ph_desc_res: "Brief service description",
  os_ph_30: "e.g. 30",
  msg_so_coord_ativos: "Only Coordinators can register assets.",
  msg_so_coord_planos: "Only Coordinators can manage plans.",
  msg_so_coord_desat_pl: "Only Coordinators can deactivate plans.",
  msg_so_coord_desat_at: "Only Coordinators can deactivate assets.",
  msg_so_coord_reat_pl: "Only Coordinators can reactivate plans.",
  msg_so_coord_reat_at: "Only Coordinators can reactivate assets.",
  msg_so_coord_excl_pl: "Only Coordinators can delete plans.",
  msg_informe_nome: "Enter the name.",
  msg_informe_desc: "Enter the description.",
  msg_informe_valor: "Enter the value.",
  msg_informe_param: "Enter the parameter.",
  msg_informe_justif: "Enter the reason for deactivating the asset.",
  msg_reativar_plano: "Reactivate this plan?",
  msg_reativar_ativo: "Reactivate this asset?",
  msg_excluir_plano: "Delete this plan?",
  msg_os_ja_aberta: "A work order is already open for this plan (WO #",
  msg_sem_plano_venc: "No plans overdue or due within 7 days.",
  msg_os_geradas: " work order(s) generated successfully!",
  pl_editar_titulo: "Edit Plan",
  pl_ac_desc_med: "Measurement description *",
  pl_ac_desc_acao: "Action description *",
  pl_ac_param: "Parameter",
  pl_ac_unidade: "Unit",
  pl_ac_lim_min: "Min limit",
  pl_ac_lim_max: "Max limit",
  an_ph_evento: "Describe the event...",
  an_6m_amb_curto: "Environ.",
  at_ph_motivo: "e.g. Obsolete equipment, awaiting replacement...",
  crit_c_hse: "HSE — Safety / Health / Environment",
  crit_c_prod: "Production / Operation",
  crit_c_custo: "Repair / Replacement Cost",
  crit_c_freq: "Failure Frequency (MTBF)",
  crit_c_det: "Failure Detectability",
  crit_c_red: "Redundancy / Failure Mode",
  msg_os_canceladas: " open work order(s) cancelled due to asset deactivation.",
  lg_msg_sessao: "Your session expired or has no company associated. Please log in again.",
  lg_msg_convite_nc: "Invite not loaded yet.",
  lg_msg_senha_curta: "Password must be at least 6 characters.",
  lg_msg_senha_dif: "Passwords do not match.",
  lg_msg_email_existe: "This e-mail already has an account. Try logging in with your existing password, or ask the coordinator to delete the duplicate user before generating a new invite.",
  lg_msg_confirme: "Account created. Confirm your e-mail and then log in.",
  lg_msg_vinc_falha: "Could not link the invite. Please try again.",
  lg_msg_criada: "Account created! Redirecting...",
  lg_msg_vinc_erro: "Error linking the invite. Your account was created — try logging in normally.",
  lg_msg_conexao: "Connection error. Please try again.",
  lg_msg_preencha: "Enter e-mail and password.",
  lg_msg_incorretos: "Incorrect e-mail or password.",
  lg_msg_sem_conta: "Account not found. Create an account.",
  lg_msg_carregar: "Error loading data. Please try again.",
  lg_msg_todos: "Fill in all fields.",
  lg_ph_email: "you@email.com",
  lg_ph_nome: "Full name",
  lg_ph_empresa: "e.g. Acme Manufacturing",
  lg_ph_min6: "Minimum 6 characters",
  lg_ph_repita: "Repeat the password",
},

// ── ESPAÑOL ────────────────────────────────────────────────────────────────
es: {
  nav_dashboard:    "Panel",
  nav_ordens:       "Ordenes de Trabajo",
  nav_ativos:       "Gestion de Activos",
  nav_cadastros:    "Configuracion",
  nav_os:           "OT",
  nav_ativos_short: "Activos",

  topbar_alert_criticas: " OT critica(s) abiertas",

  dash_status:      "Estado Operacional",
  dash_confiab:     "Confiabilidad y Disponibilidad",
  dash_gestao:      "Gestion del Mantenimiento",
  dash_criticidade: "Criticidad de Activos (NORSOK Z-008 / API RP 581)",
  dash_ultimas_os:  "Ultimas Ordenes de Trabajo",
  dash_equipamentos:"Equipos",
  dash_planos:      "Atencion Requerida",
  dash_ver_todas:   "Ver todas →",
  dash_calcular:    "Calcular en la ficha del activo →",
  dash_planos_ok:   "✓ Todos los planes al dia",

  kpi_abertas:      "OT Abiertas",
  kpi_andamento:    "En Progreso",
  kpi_criticas:     "OT Criticas",
  kpi_equipamentos: "Equipos",
  kpi_mtbf:         "MTBF Global",
  kpi_mttr:         "MTTR Global",
  kpi_disponib:     "Dispon.",
  kpi_manuplan:     "Mant. Planificado",
  kpi_compliance:   "Cumplimiento",
  kpi_backlog:      "Backlog",
  kpi_falhas:       "Fallos Correct.",
  kpi_aguardando:   "esperando",
  kpi_em_exec:      "en progreso",
  kpi_prio_max:     "prioridad max",
  kpi_operando:     "funcionando",

  crit_matriz:      "Matriz de Riesgo (Consecuencia x Probabilidad)",
  crit_ativos:      "Activos por Criticidad",
  crit_eixo_y:      "Eje Y: Consecuencia",
  crit_eixo_x:      "Eje X: Probabilidad",
  crit_score:       "Puntuacion de Criticidad (0-100)",
  crit_warn_super:  "% de activos clasificados como Criticos — por encima del limite del 30% (NORSOK Z-008). Recalibrar criterios.",
  crit_ok_bench:    "✓ Distribucion dentro del benchmark (5-15% criticos) — NORSOK Z-008",
  crit_vazio:       'Abra la ficha de cada activo y calcule la criticidad en la pestaña "Criticidad".',
  crit_mais:        "+mas ",
  crit_avaliados:   " activos evaluados",
  crit_classes:     {A:"Critico", B:"Alto", C:"Medio", D:"Bajo"},
  crit_recs: {
    A: "Monitoreo continuo (predictivo). Plan de contingencia obligatorio. FMEA y analisis de causa raiz.",
    B: "Mantenimiento preventivo sistematico. Monitoreo por condicion recomendado.",
    C: "Preventivo basado en tiempo o ciclos. Evaluar costo-beneficio predictivo.",
    D: "Correctivo planificado aceptable (run-to-failure). Garantizar repuestos disponibles."
  },

  ord_titulo:       "Ordenes de Trabajo",
  ord_nova:         "+ Nueva OT",
  ord_filtro_todas: "Todas",
  ord_tipo_label:   "Tipo de Mantenimiento",
  ord_tipo_corr:    "Correctivo",
  ord_tipo_prev:    "Preventivo",
  ord_tipo_pred:    "Predictivo",
  ord_prio_label:   "Prioridad",
  ord_prio_crit:    "Critica",
  ord_prio_alta:    "Alta",
  ord_prio_normal:  "Normal",
  ord_prio_baixa:   "Baja",
  ord_status_aberta:"Abierta",
  ord_status_and:   "En Progreso",
  ord_status_conc:  "Completada",
  ord_status_canc:  "Cancelada",
  ord_iniciar:      "▶ Iniciar Ejecucion",
  ord_registrar:    "+ Registrar Actividad",
  ord_concluir:     "✓ Completar OT",
  ord_cancelar:     "✕ Cancelar",
  ord_finalizada:   "OT cerrada",
  ord_sem_prazo:    "Sin fecha limite",
  ord_atribuida_a:  "OT asignada a",
  ord_periodo:      "Periodo",
  ord_proxima_em:   "Proxima OT en",
  ord_reg_exec:     "Registro de Ejecucion",
  ord_sem_reg:      "Sin registros aun",
  ord_inicia_para_reg:"Inicie la OT para comenzar a registrar",
  ord_total_pecas:  "en piezas",
  ord_nenhuma:      "Ninguna OT encontrada",
  ord_nenhuma_cad:  "Ninguna OT registrada",
  ord_f_titulo:     "Titulo *",
  ord_f_ativo:      "Activo *",
  ord_f_tipo:       "Tipo",
  ord_f_prio:       "Prioridad",
  ord_f_tecnico:    "Tecnico Asignado",
  ord_f_prazo:      "Fecha limite",
  ord_f_periodo:    "Periodo (dias)",
  ord_f_proxima:    "Proxima OT en (dias)",
  ord_f_descricao:  "Descripcion / Sintoma",
  ord_f_ativo_label:"Activo",
  ord_f_abertura:   "Apertura",
  ord_f_tipo2:      "Tipo",
  exec_tipo_obs:    "Observacion",
  exec_tipo_med:    "Medicion",
  exec_tipo_peca:   "Pieza / Material",
  exec_tipo_foto:   "Foto",
  exec_param:       "Parametro medido",
  exec_valor:       "Valor medido *",
  exec_limite:      "Limite / Referencia",
  exec_cond:        "Condicion",
  exec_cond_normal: "Normal",
  exec_cond_atenc:  "Atencion",
  exec_cond_crit:   "Critico",
  exec_cond_fora:   "Fuera de especificacion",
  exec_peca_desc:   "Descripcion de la pieza *",
  exec_qty:         "Cantidad",
  exec_custo:       "Costo unitario ($)",
  exec_foto_desc:   "Descripcion de la foto",
  exec_ultimo_reg:  "Ultimo registro",
  exec_qtd_reg:     " registros",

  at_titulo:        "Gestion de Activos",
  at_ficha:         "Ficha: ",
  at_novo:          "+ Nuevo Activo",
  at_clique:        "Toque un activo para abrir su ficha",
  at_nenhum:        "Ningun activo registrado",
  at_tabs: {
    geral:"General", indicadores:"Indicadores", historico:"Historial",
    preventiva:"Plan de Mantenimiento", preditiva:"Mediciones",
    documentos:"Documentos", criticidade:"Criticidad"
  },
  at_info_fabricante:"Fabricante",
  at_info_modelo:    "Modelo",
  at_info_serie:     "N° de Serie",
  at_info_ano:       "Año",
  at_info_local:     "Ubicacion",
  at_info_cat:       "Categoria",
  at_info_tag:       "Tag",
  at_info_pat:       "N° Patrimonio",
  at_info_empresa:   "Empresa",
  at_info_unidade:   "Unidad",
  at_resumo:         "Resumen y Ultima Intervencion",
  at_intervencoes:   "Intervenciones",
  at_corretivas:     "Correctivos",
  at_horas:          "Horas de Mant.",
  at_ultima_int:     "Ultima Intervencion",
  at_sem_hist:       "Sin registros de mantenimiento",
  at_sel_ind:        "Seleccionar Indicadores",
  at_sel_ind_sub:    "Haga clic para activar o desactivar cada indicador.",
  at_nenhum_ind:     "Ningun indicador activado. Seleccione abajo.",
  at_reg_manut:      "+ Registrar Mantenimiento",
  at_registros:      " registro(s)",
  at_sem_manut:      "Ningun mantenimiento registrado aun.",
  at_novo_plano:     "+ Nuevo Plan",
  at_nenhum_plano:   "Ningun plan preventivo registrado",
  at_planos_atraso:  " plan(es) requieren atencion",
  at_nova_leitura:   "+ Nueva Lectura",
  at_sem_leituras:   "Ninguna lectura predictiva registrada.",
  at_mais_leituras:  "Agregue mas lecturas para generar el grafico",
  at_acima_limite:   "Ultimo valor por encima del limite de alerta!",
  at_valor_med:      "Valor medido",
  at_limite:         "Limite",
  at_anexar:         "Haga clic para adjuntar documentos",
  at_anexar_sub:     "PDF, Word, Excel, Imagenes, ZIP",
  at_sem_docs:       "Ningun documento adjunto",
  at_baixar:         "Descargar",
  at_status_op:      "Operacional",
  at_status_manut:   "En Mantenimiento",
  at_status_par:     "Parado",
  at_anal_titulo:    "Analisis de Falla",
  at_anal_sem:       "Mantenimiento correctivo sin analisis de falla",
  at_anal_add:       "+ Analisis de Falla",
  at_anal_editar:    "editar",
  at_anal_salvar:    "Guardar Analisis",
  at_anal_tipos: {
    "5porques":"5 Porqués", "ishikawa":"Ishikawa (6M)",
    "fmea":"FMEA", "rca":"RCA",
    "fta":"Arbol de Fallos", "pdca":"PDCA"
  },

  cad_titulo:         "Configuracion",
  cad_tab_usuarios:   "Usuarios",
  cad_tab_categorias: "Categorias",
  cad_tab_empresas:   "Empresas",
  cad_novo_user:      "+ Nuevo Usuario",
  cad_nova_cat:       "+ Nueva Categoria",
  cad_nova_emp:       "+ Nueva Empresa",
  cad_add_unid:       "+ Agregar Unidad",
  cad_ativos_label:   " activo(s)",
  cad_unidades_label: " unidad(es)",
  cad_inativar:       "Desactivar",
  cad_ativar:         "Activar",
  cad_excluir:        "Eliminar",
  cad_nenhuma_emp:    "Ninguna empresa registrada",
  cad_perfis: {Coordenador:"Coordinador", Tecnico:"Tecnico", Visualizador:"Visualizador"},
  cad_f_nome:         "Nombre completo *",
  cad_f_email:        "Correo electronico *",
  cad_f_telefone:     "Telefono",
  cad_f_senha:        "Contraseña",
  cad_f_perfil:       "Perfil",
  cad_f_status:       "Estado",
  cad_f_ativo:        "✓ Activo",
  cad_f_inativo:      "✕ Inactivo",
  cad_f_cat_nome:     "Nombre de la categoria *",
  cad_f_cat_desc:     "Descripcion",
  cad_f_cat_icone:    "Icono",
  cad_f_cat_cor:      "Color",
  cad_f_cat_prev:     "Vista previa",
  cad_f_emp_nome:     "Nombre / Razon social *",
  cad_f_emp_cnpj:     "ID Fiscal",
  cad_f_emp_tel:      "Telefono",
  cad_f_emp_end:      "Direccion",
  cad_f_emp_cont:     "Persona de contacto",
  cad_f_unid_nome:    "Nombre de la unidad *",
  cad_f_unid_end:     "Direccion / Ubicacion",
  cad_f_unid_resp:    "Responsable",

  at_f_nome:"Nombre *", at_f_cat:"Categoria", at_f_empresa:"Empresa",
  at_f_unidade:"Unidad", at_f_local:"Ubicacion", at_f_fab:"Fabricante",
  at_f_modelo:"Modelo", at_f_serie:"N° de Serie", at_f_ano:"Año",
  at_f_tag:"Tag", at_f_pat:"N° Patrimonio",

  h_f_desc:"Descripcion *", h_f_data:"Fecha", h_f_tipo:"Tipo",
  h_f_tecnico:"Tecnico", h_f_horas:"Horas", h_f_custo:"Costo ($)",
  h_f_prox:"Proximo (dias)", h_f_obs:"Observaciones",

  pl_f_nome:"Nombre *", pl_f_freq:"Frecuencia",
  pl_f_prox:"Proxima Ejecucion", pl_f_resp:"Responsable",
  pl_freq: {
    Semanal:"Semanal", Quinzenal:"Quincenal", Mensal:"Mensual",
    Bimestral:"Bimestral", Trimestral:"Trimestral",
    Semestral:"Semestral", Anual:"Anual"
  },
  pl_ok:"OK", pl_atrasado:"Atrasado", pl_vence:"Vence Hoy",
  pl_todos_ok:"✓ Todos los planes al dia",
  pl_nenhuma_os:"Ninguna orden registrada",

  ind_names: {
    mtbf:"Tiempo Medio entre Fallos", mttr:"Tiempo Medio de Reparacion",
    disp:"Disponibilidad", conf:"Confiabilidad 1000h",
    lambda:"Tasa de Fallos", manuplan:"Mantenimiento Planificado",
    backlog:"Backlog de OT", nfalhas:"Numero de Fallos",
    compliance:"Cumplimiento Preventivo", mttf:"Tiempo Medio hasta Fallo",
    downtime:"Horas Inactivas", oee_a:"Disponibilidad OEE"
  },
  ind_abbrs: {
    mtbf:"MTBF", mttr:"MTTR", disp:"D(%)", conf:"R(t)",
    lambda:"Tasa-F", manuplan:"MP%", backlog:"BKL",
    nfalhas:"NF", compliance:"CP%", mttf:"MTTF",
    downtime:"DT", oee_a:"OEE-D"
  },

  btn_salvar:"Guardar", btn_cancelar:"Cancelar", btn_editar:"Editar",
  btn_excluir:"Eliminar", btn_voltar:"← Volver", btn_novo:"+ Nuevo",
  btn_cadastrar:"Registrar", btn_criar_os:"Crear OT",
  btn_selecione:"Seleccione...", btn_sel_emp:"Seleccione empresa...",
  btn_sel_unid:"Seleccione unidad...", btn_sem_emp:"Ninguna empresa registrada",

  // ── NAV / COMUN (nuevo) ─────────────────────────────────────────────────
  nav_calendario:  "Calendario",
  nav_relatorios:  "Informes",
  nav_recolher:    "Contraer",
  nav_cal_short:   "Cal.",
  nav_rel_short:   "Inf.",
  btn_sair:        "Salir",
  msg_sair:        "¿Salir de Mantenedor?",
  msg_sem_permissao: "Esta area esta restringida al perfil Coordinador.",
  msg_erro_empresa:  "Error al guardar los datos de la empresa: ",
  msg_sem_empresa:   "No se pudo guardar: la sesion no tiene empresa asociada. Inicie sesion nuevamente.",

  title_dashboard:     "Panel",
  title_ordens:        "Ordenes de Trabajo",
  title_ativos:        "Gestion de Activos",
  title_cadastros:     "Configuracion",
  title_calendario:    "Calendario",
  title_relatorios:    "Informes",
  title_os_corretiva:  "OT Correctiva",
  title_os_programada: "OT Preventiva / Predictiva",
  title_login:         "Iniciar sesion",

  // ── CALENDARIO ──────────────────────────────────────────────────────────
  cal_mes:         "Mes",
  cal_semana:      "Semana",
  cal_hoje:        "Hoy",
  cal_sem_eventos: "Sin eventos",
  cal_os_mes: "OT del Mes",
  cal_planos: "Planes",
  cal_criticas: "Criticas",
  cal_atrasados: "Atrasados",
  cal_os_plano: "OT Plan",
  cal_plano: "Plan",
  cal_plano_suf: " — Plan",
  cal_meses:       ["Enero","Febrero","Marzo","Abril","Mayo","Junio",
                    "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
  cal_meses_short: ["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"],
  cal_dias:        ["Dom","Lun","Mar","Mie","Jue","Vie","Sab"],

  // ── INFORMES ────────────────────────────────────────────────────────────
  rel_titulo:       "Informes",
  rel_tipo_os:      "OT Realizadas",
  rel_tipo_hist:    "Historial de Activos",
  rel_filtros:      "Filtros",
  rel_limpar:       "Limpiar filtros",
  rel_imprimir:     "Imprimir / PDF",
  rel_todos:        "Todos",
  rel_status:       "Estado",
  rel_prazo:        "Fecha limite",
  rel_abertura:     "Apertura",
  rel_prioridade:   "Prioridad",
  rel_tecnico:      "Tecnico Asignado",
  rel_de:           "Desde:",
  rel_ate:          "Hasta: ",
  rel_ativo:        "Activo: ",
  rel_status_lbl:   "Estado: ",
  rel_empresa:      "Empresa (contratista/cliente)",
  rel_unidade:      "Unidad",
  rel_unidade_lbl:  "Unidad:",
  rel_buscar_os:    "Buscar OT por numero",
  rel_num_exemplo:  "Ej.: 2026-COR-0004",
  rel_informe_num:  "Ingrese el numero de la OT.",
  rel_nao_encontrada: "Ninguna OT encontrada con el numero ",
  rel_concluidas:   "Completadas",
  rel_em_aberto:    "Abiertas",
  rel_criticas:     "Criticas",
  rel_custo_total:  "Costo total",
  rel_horas_total:  "Horas totales",
  rel_registros:    "Registros",
  rel_analise:      "Analisis",
  rel_com_analise:  "Con analisis de falla",
  rel_sem_analise:  "Sin analisis de falla",
  rel_com_e_sem:    "Con y sin analisis",
  rel_sim:          "Si",
  rel_nao:          "No",
  rel_gerado_em:    "Generado el ",
  rel_cnpj:         "ID Fiscal ",
  rel_cliente: "Cliente:",
  rel_endereco: "Direccion:",
  rel_tipo_lbl: "Tipo: ",
  rel_filtros_apl: "Filtros aplicados: ",
  rel_titulo_os_rel: "Informe de Ordenes de Trabajo",
  rel_titulo_hist_rel: "Informe de Historial de Mantenimiento",
  rel_todas_unidades: "Todas las unidades",
  rel_todos_ativos: "Todos los activos",
  rel_todas_empresas: "Todas las empresas",
  rel_data_inicio: "Fecha inicio",
  rel_data_fim: "Fecha fin",
  rel_imprimir_pdf: "Imprimir / Guardar PDF",
  rel_imprimir_os: "Imprimir una OT especifica (numero)",
  rel_buscar_impr: "Buscar e imprimir",
  rel_total: "Total",
  rel_vazio_os: "Ninguna OT encontrada con los filtros seleccionados.",
  rel_vazio_hist: "Ningun registro de mantenimiento encontrado.",
  rel_mista: "Mixta",
  rel_dados_gerais: "Datos Generales",
  rel_desc_servico: "Descripcion del Servicio Solicitado",
  rel_obs_tec: "Observaciones Tecnicas",
  rel_med_reg: "Mediciones Registradas",
  rel_pecas_mat: "Piezas y Materiales Utilizados",
  rel_reg_foto: "Registros Fotograficos",
  rel_checklist: "Lista de Verificacion de Planes",
  rel_aceite: "Responsable del Cliente — Aceptacion del Servicio",
  rel_tec_exec: "Tecnico Ejecutante",
  rel_col_param: "Parametro",
  rel_col_valor: "Valor",
  rel_col_limite: "Limite",
  rel_col_cond: "Condicion",
  rel_col_desc: "Descripcion",
  rel_col_qtd: "Cant",
  rel_col_custo_un: "Costo Unit.",
  rel_col_subtotal: "Subtotal",
  rel_col_data: "Fecha",
  rel_col_horas: "Horas",
  rel_col_custo: "Costo",
  rel_total_horas: "Horas totales: ",
  rel_total_pecas: "Total en piezas: ",
  an_porque: "Por que ",
  an_causa_raiz: "Causa raiz:",
  an_acao_corr: "Accion correctiva:",
  an_modo_falha: "Modo de falla:",
  an_efeito: "Efecto:",
  an_causa: "Causa:",
  an_npr: "NPR:",
  an_acao: "Accion:",
  an_descricao: "Descripcion:",

  // ── CONFIGURACION (complemento) ─────────────────────────────────────────
  cad_acesso:        "Acceso al sistema",
  cad_convite_ger:   "Invitacion generada",
  cad_convite_pend:  "Invitacion pendiente",
  cad_copiar_link:   "Copiar enlace",
  cad_fechar:        "Cerrar",
  cad_nova_unid:     "Nueva Unidad",
  cad_salvar_emp:    "Guardar datos de la empresa",
  cad_coords:        "Coord.",
  cad_tecnicos:      "Tecnicos",
  cad_inativos:      "Inactivos",
  cad_sem_desc:      "Sin descripcion",
  cad_cats_cad:      " categorias registradas",
  cad_emps_cad:      " empresa(s)",
  cad_contato_resp:  "Contacto / Responsable tecnico",
  cad_contato:       "Persona de contacto",
  cad_contato_lbl:   "Contacto: ",
  cad_resp_lbl:      "Resp: ",
  cad_razao_social:  "Razon social / Nombre *",
  cad_unid_nome:     "Nombre de la unidad *",
  cad_novo_user_tit: "Nuevo Usuario",
  cad_nova_cat_tit:  "Nueva Categoria",
  cad_nova_emp_tit:  "Nueva Empresa",

  // ── LOGIN ───────────────────────────────────────────────────────────────
  lg_entrar:        "Iniciar sesion",
  lg_criar_conta:   "Crear Cuenta",
  lg_criar_gratis:  "Crear Cuenta Gratis",
  lg_email:         "Correo electronico",
  lg_senha:         "Contraseña",
  lg_conf_senha:    "Confirme la contraseña",
  lg_crie_senha:    "Cree una contraseña",
  lg_seu_nome:      "Su Nombre",
  lg_empresa:       "Nombre de la Empresa",
  lg_empresa_hint:  "Sera el nombre de su cuenta en Mantenedor",
  lg_plano_inclui:  "plan gratuito incluye",
  lg_ativos_ilim:   "✓ Activos ilimitados",
  lg_os_ilim:       "✓ OT ilimitadas",
  lg_planos_manut:  "✓ Planes de mantenimiento",
  lg_relatorios:    "✓ Informes",
  lg_termos:        "Terminos",
  lg_privacidade:   "Privacidad",
  lg_carregando:    "Cargando invitacion...",
  at_sel_empresa: "Seleccione empresa...",
  at_sel_unidade: "Seleccione unidad...",
  at_cad_ativo: "Registrar Activo",
  at_editar_ativo: "Editar Activo",
  h_tipo_insp: "Inspeccion",
  at_ph_nome: "Nombre del equipo",
  at_ph_local: "Ej: Nave A, Linea 1",
  at_ph_ano: "Ej: 2020",
  at_ph_tag: "Ej: COMP-002",
  at_ph_pat: "Ej: PAT-0001",
  h_ph_desc: "¿Que se hizo?",
  pl_novo_titulo: "Nuevo Plan",
  pl_ph_nome: "Ej: Lubricacion mensual",
  pl_acoes: "Acciones / Mediciones del Plan",
  pl_add_acao: "+ Accion (checklist)",
  pl_add_med: "+ Medicion",
  pl_salvar: "Guardar Plan",
  pr_nova_titulo: "Nueva Lectura Predictiva",
  pr_lim_alerta: "Limite de alerta",
  pr_unidade: "Unidad",
  pr_ph_param: "Ej: Vibracion, Temperatura, Presion...",
  pr_ph_unidade: "Ej: mm/s, C, bar...",
  pr_ph_obs: "Condicion observada...",
  pr_params: {vib:"Vibracion (mm/s)", temp:"Temperatura (C)", ruido:"Ruido (dB)", pres:"Presion (bar)", corr:"Corriente (A)", esp:"Espesor (mm)", outro:"Otro"},
  an_titulo: "Analisis de Falla",
  an_problema: "Problema observado",
  an_ph_problema: "Describa la falla observada...",
  an_causa_raiz_l: "Causa Raiz",
  an_ph_causa_pq: "Respuesta final — causa fundamental...",
  an_acao_corr_l: "Accion Correctiva",
  an_salvar: "Guardar Analisis",
  an_5pq_hint: "Pregunte \"¿por que?\" sucesivamente hasta llegar a la causa raiz.",
  an_ish_hint: "Diagrama Espina de Pescado: identifique causas en las 6M.",
  an_ish_efeito: "Efecto / Falla Central",
  an_ish_ph_ef: "Ej: Parada no planificada del equipo",
  an_6m_mo: "Mano de Obra",
  an_6m_maq: "Maquina",
  an_6m_met: "Metodo",
  an_6m_mat: "Material",
  an_6m_amb: "Medio Ambiente",
  an_6m_med: "Medicion",
  an_6m_ph_mo: "Error operativo, capacitacion...",
  an_6m_ph_maq: "Desgaste, falta de mantenimiento...",
  an_6m_ph_met: "Procedimiento, estandar...",
  an_6m_ph_mat: "Calidad, especificacion...",
  an_6m_ph_amb: "Temperatura, humedad...",
  an_6m_ph_med: "Instrumento, monitoreo...",
  an_ish_causa: "Causa Raiz Predominante",
  an_ish_ph_causa: "¿Cual de las 6M fue la causa principal?",
  an_fmea_modo: "Modo de Falla",
  an_fmea_ph_modo: "Ej: Rotura de rodamiento",
  an_fmea_efeito: "Efecto",
  an_fmea_ph_ef: "Ej: Parada del equipo",
  an_fmea_causa: "Causa",
  an_fmea_ph_causa: "Ej: Lubricacion insuficiente",
  an_fmea_ctrl: "Control Actual",
  an_fmea_ph_ctrl: "Ej: Inspeccion visual mensual",
  an_fmea_sev: "Severidad (S) 1-10",
  an_fmea_ocor: "Ocurrencia (O) 1-10",
  an_fmea_det: "Deteccion (D) 1-10",
  an_fmea_sem_ef: "Sin efecto",
  an_fmea_catast: "Catastrofico",
  an_fmea_improv: "Improbable",
  an_fmea_certo: "Seguro",
  an_fmea_detect: "Detectable",
  an_fmea_indet: "Indetectable",
  an_fmea_rpn: "NPR = S × O × D",
  an_fmea_acao_rec: "Accion Recomendada",
  an_fmea_resp: "Responsable / Plazo",
  an_fmea_ph_resp: "Ej: Juan Perez — hasta 30/06/2026",
  an_rca_hint: "Root Cause Analysis: cadena de eventos que llevo a la falla.",
  an_rca_decl: "Declaracion del Problema",
  an_rca_ph_decl: "Que fallo, cuando, como y con que frecuencia...",
  an_rca_time: "Linea de Tiempo",
  an_rca_ph_time: "14h00 — operador noto ruido\n15h00 — parada de emergencia...",
  an_rca_fat: "Factores Contribuyentes",
  an_rca_ph_fat: "Factores humanos, tecnicos, organizacionales...",
  an_rca_ph_causa: "La causa fundamental...",
  an_rca_acoes: "Acciones Correctivas",
  an_rca_verif: "Verificacion de la Eficacia",
  an_rca_ph_verif: "¿Como y cuando verificar?",
  an_fta_topo: "Evento Cima",
  an_fta_ph_topo: "Ej: Parada no planificada",
  an_fta_diretas: "Causas Directas",
  an_fta_basicas: "Causas Basicas (raiz)",
  an_fta_add: "+ Agregar",
  an_fta_porta: "Puerta Logica",
  an_fta_and: "AND — todas las causas juntas",
  an_fta_or: "OR — cualquier causa es suficiente",
  an_fta_acao: "Accion Preventiva",
  an_pdca_hint: "Ciclo PDCA para resolucion y mejora continua.",
  an_pdca_p: "P — Planificar",
  an_pdca_d: "D — Hacer",
  an_pdca_c: "C — Verificar",
  an_pdca_a: "A — Actuar",
  an_pdca_ph_p: "¿Cual es el problema? ¿Meta? ¿Que hacer?",
  an_pdca_ph_d: "¿Quien? ¿Cuando? ¿Como?",
  an_pdca_ph_c: "¿Como medir el resultado?",
  an_pdca_ph_a: "¿Que estandarizar? ¿Ajustar?",
  an_fmea_hint: "NPR = Severidad × Ocurrencia × Deteccion. Por encima de 100 exige accion inmediata.",
  an_fta_hint: "Arbol de Fallos: partiendo del evento cima, identifique causas por puertas logicas.",
  enum_labels: {
    "Aberta":"Abierta",
    "Em Andamento":"En Progreso",
    "Concluida":"Completada",
    "Cancelada":"Cancelada",
    "Critica":"Critica",
    "Alta":"Alta",
    "Normal":"Normal",
    "Baixa":"Baja",
    "Corretiva":"Correctivo",
    "Preventiva":"Preventivo",
    "Preditiva":"Predictivo",
    "Mista":"Mixta",
    "Inspecao":"Inspeccion",
    "Operacional":"Operacional",
    "Em Manutencao":"En Mantenimiento",
    "Parado":"Detenido",
    "Desativado":"Desactivado",
    "OK":"OK",
    "Atrasado":"Atrasado",
    "Vence Hoje":"Vence Hoy",
    "Vence em Breve":"Vence Pronto",
    "Ambos":"Ambos"
  },
  crit_alto_plano: "ALTO — Plan necesario",
  crit_baixo_aceit: "BAJO — Aceptable",
  crit_critico_imed: "CRITICO — Accion inmediata",
  crit_medio_monit: "MEDIO — Monitorear",
  an_lbl_acao: "Accion:",
  an_lbl_acoes: "Acciones:",
  an_lbl_analise: "Analisis:",
  an_lbl_causa_raiz: "Causa raiz:",
  an_lbl_causa: "Causa:",
  an_lbl_efeito: "Efecto:",
  an_lbl_evento_topo: "Evento cima:",
  an_lbl_modo: "Modo:",
  an_lbl_problema: "Problema:",
  at_desativar: "Desactivar",
  at_reativar: "Reactivar",
  at_desat_titulo: "Desactivar Activo",
  at_justificativa: "Justificacion *",
  at_gerar_os: "Generar OT",
  at_info_equip: "Informacion del Equipo",
  at_nenhum_plano_cad: "Ningun plan registrado",
  cad_ph_desc_breve: "Descripcion breve...",
  os_confirmar_concl: "¿Confirmar la finalizacion de esta OT?",
  os_informe_desc: "Ingrese la descripcion.",
  os_informe_peca: "Ingrese la pieza.",
  os_informe_val_med: "Ingrese el valor medido.",
  os_sel_imagem: "Seleccione una imagen.",
  os_ativo_invalido: "Activo invalido.",
  os_preencha_tit: "Complete titulo y activo.",
  os_nao_encontrada: "OT no encontrada para id:",
  os_gerar_prog: "Generar OT Programadas",
  os_executar: "Ejecutar",
  os_iniciar_exec: "Iniciar Ejecucion",
  os_acima_max: "¡Por encima del limite maximo!",
  os_abaixo_min: "¡Por debajo del limite minimo!",
  os_ph_peca: "Ej: Rodamiento SKF 6205",
  os_ph_cod_forn: "Codigo, proveedor...",
  os_ph_contexto: "Contexto o detalle...",
  os_ph_foto: "Lo que muestra la foto...",
  os_ph_obs: "Lo que fue observado, hecho o encontrado...",
  os_ph_desc_prob: "Describa el problema o servicio a realizar...",
  os_ph_desc_serv: "Describa el servicio a realizar...",
  os_ph_desc_res: "Descripcion resumida del servicio",
  os_ph_30: "Ej: 30",
  msg_so_coord_ativos: "Solo los Coordinadores pueden registrar activos.",
  msg_so_coord_planos: "Solo los Coordinadores pueden gestionar planes.",
  msg_so_coord_desat_pl: "Solo los Coordinadores pueden desactivar planes.",
  msg_so_coord_desat_at: "Solo los Coordinadores pueden desactivar activos.",
  msg_so_coord_reat_pl: "Solo los Coordinadores pueden reactivar planes.",
  msg_so_coord_reat_at: "Solo los Coordinadores pueden reactivar activos.",
  msg_so_coord_excl_pl: "Solo los Coordinadores pueden eliminar planes.",
  msg_informe_nome: "Ingrese el nombre.",
  msg_informe_desc: "Ingrese la descripcion.",
  msg_informe_valor: "Ingrese el valor.",
  msg_informe_param: "Ingrese el parametro.",
  msg_informe_justif: "Ingrese la justificacion para desactivar el activo.",
  msg_reativar_plano: "¿Reactivar este plan?",
  msg_reativar_ativo: "¿Reactivar este activo?",
  msg_excluir_plano: "¿Eliminar este plan?",
  msg_os_ja_aberta: "Ya existe una OT abierta para este plan (OT #",
  msg_sem_plano_venc: "Ningun plan vencido o con vencimiento en 7 dias.",
  msg_os_geradas: " OT generada(s) con exito!",
  pl_editar_titulo: "Editar Plan",
  pl_ac_desc_med: "Descripcion de la medicion *",
  pl_ac_desc_acao: "Descripcion de la accion *",
  pl_ac_param: "Parametro",
  pl_ac_unidade: "Unidad",
  pl_ac_lim_min: "Limite min",
  pl_ac_lim_max: "Limite max",
  an_ph_evento: "Describa el evento...",
  an_6m_amb_curto: "Medio Amb.",
  at_ph_motivo: "Ej: Equipo obsoleto, esperando reemplazo...",
  crit_c_hse: "HSE — Seguridad / Salud / Medio Ambiente",
  crit_c_prod: "Produccion / Operacion",
  crit_c_custo: "Costo de Reparacion / Sustitucion",
  crit_c_freq: "Frecuencia de Falla (MTBF)",
  crit_c_det: "Detectabilidad de la Falla",
  crit_c_red: "Redundancia / Modo de Falla",
  msg_os_canceladas: " OT abierta(s) cancelada(s) por desactivacion del activo.",
  lg_msg_sessao: "Su sesion expiro o no tiene empresa asociada. Inicie sesion nuevamente.",
  lg_msg_convite_nc: "Invitacion aun no cargada.",
  lg_msg_senha_curta: "La contraseña debe tener al menos 6 caracteres.",
  lg_msg_senha_dif: "Las contraseñas no coinciden.",
  lg_msg_email_existe: "Este correo ya tiene una cuenta. Intente iniciar sesion con su contraseña actual, o pida al coordinador que elimine el usuario duplicado antes de generar una nueva invitacion.",
  lg_msg_confirme: "Cuenta creada. Confirme su correo y luego inicie sesion.",
  lg_msg_vinc_falha: "No se pudo vincular la invitacion. Intente nuevamente.",
  lg_msg_criada: "¡Cuenta creada! Redirigiendo...",
  lg_msg_vinc_erro: "Error al vincular la invitacion. Su cuenta fue creada — intente iniciar sesion.",
  lg_msg_conexao: "Error de conexion. Intente nuevamente.",
  lg_msg_preencha: "Ingrese correo y contraseña.",
  lg_msg_incorretos: "Correo o contraseña incorrectos.",
  lg_msg_sem_conta: "Cuenta no encontrada. Cree una cuenta.",
  lg_msg_carregar: "Error al cargar los datos. Intente nuevamente.",
  lg_msg_todos: "Complete todos los campos.",
  lg_ph_email: "usted@correo.com",
  lg_ph_nome: "Nombre completo",
  lg_ph_empresa: "Ej: Metalurgica Buenos Aires",
  lg_ph_min6: "Minimo 6 caracteres",
  lg_ph_repita: "Repita la contraseña",
}

}; // end TRANSLATIONS

// ── API PÚBLICA ──────────────────────────────────────────────────────────────
var LANG_KEY = "mx_lang";
var _current  = localStorage.getItem(LANG_KEY) || "pt";

function get(key){
  var d = TRANSLATIONS[_current] || TRANSLATIONS["pt"];
  return d[key] !== undefined ? d[key] : (TRANSLATIONS["pt"][key] || key);
}

function current(){ return _current; }

function set(lang){
  if(!TRANSLATIONS[lang]) return;
  _current = lang;
  localStorage.setItem(LANG_KEY, lang);
  syncHtmlLang();
}

var HTML_LANG = {pt:"pt-BR", en:"en", es:"es"};
function syncHtmlLang(){
  if(document.documentElement) document.documentElement.lang = HTML_LANG[_current] || _current;
}

// Aplica traducoes em elementos estaticos marcados com data-i18n.
// Suporta data-i18n (textContent), data-i18n-ph (placeholder),
// data-i18n-title (title) e data-i18n-html (innerHTML).
function applyStatic(root){
  var r = root || document;
  if(!r.querySelectorAll) return;
  r.querySelectorAll("[data-i18n]").forEach(function(el){
    var v = get(el.getAttribute("data-i18n"));
    if(typeof v === "string") el.textContent = v;
  });
  r.querySelectorAll("[data-i18n-html]").forEach(function(el){
    var v = get(el.getAttribute("data-i18n-html"));
    if(typeof v === "string") el.innerHTML = v;
  });
  r.querySelectorAll("[data-i18n-ph]").forEach(function(el){
    var v = get(el.getAttribute("data-i18n-ph"));
    if(typeof v === "string") el.placeholder = v;
  });
  r.querySelectorAll("[data-i18n-title]").forEach(function(el){
    var v = get(el.getAttribute("data-i18n-title"));
    if(typeof v === "string") el.title = v;
  });
  // Lookups em dicionarios aninhados (o value do <option> permanece em PT,
  // pois e o valor gravado no banco — so o rotulo e traduzido)
  r.querySelectorAll("[data-i18n-freq]").forEach(function(el){
    var d = get("pl_freq"), k = el.getAttribute("data-i18n-freq");
    if(d && typeof d[k] === "string") el.textContent = d[k];
  });
  r.querySelectorAll("[data-i18n-param]").forEach(function(el){
    var d = get("pr_params"), k = el.getAttribute("data-i18n-param");
    if(d && typeof d[k] === "string") el.textContent = d[k];
  });
  r.querySelectorAll("[data-i18n-anal]").forEach(function(el){
    var d = get("at_anal_tipos"), k = el.getAttribute("data-i18n-anal");
    if(d && typeof d[k] === "string") el.textContent = d[k];
  });
  r.querySelectorAll("[data-i18n-perfil]").forEach(function(el){
    var d = get("cad_perfis"), k = el.getAttribute("data-i18n-perfil");
    if(d && typeof d[k] === "string") el.textContent = d[k];
  });
  // <title> da aba do navegador
  var tk = document.body && document.body.getAttribute("data-i18n-doctitle");
  if(tk) document.title = "Mantenedor — " + get(tk);
}

function addToggle(){
  document.addEventListener("DOMContentLoaded", function(){
    // #topbar nas paginas internas; #lang-slot em telas sem topbar (login)
    var topbar = document.getElementById("topbar") || document.getElementById("lang-slot");
    if(!topbar) return;

    var btn = document.createElement("button");
    btn.id    = "lang-btn";
    btn.title = "Change language / Idioma";
    btn.style.cssText = [
      "background:transparent",
      "border:1px solid var(--border,#1e3a5f)",
      "border-radius:8px",
      "padding:5px 9px",
      "cursor:pointer",
      "font-size:12px",
      "font-weight:700",
      "letter-spacing:.03em",
      "transition:all .2s",
      "flex-shrink:0",
      "color:inherit"
    ].join(";");

    var LABELS = {pt:"PT", en:"EN", es:"ES"};
    var ORDER  = ["pt","en","es"];

    function update(){
      btn.textContent = LABELS[_current] || _current.toUpperCase();
    }
    update();

    btn.onclick = function(){
      var idx  = ORDER.indexOf(_current);
      var next = ORDER[(idx + 1) % ORDER.length];
      set(next);
      update();
      applyStatic();
      // Dispara evento para que os HTMLs possam re-renderizar
      window.dispatchEvent(new CustomEvent("langchange", {detail:{lang:next}}));
    };

    // Insere antes do botao de logout, para que o logout fique sempre
    // como o ultimo item (mais a direita) do topbar
    var logoutBtn = document.getElementById("logout-btn");
    if(logoutBtn && logoutBtn.parentNode === topbar){
      topbar.insertBefore(btn, logoutBtn);
    } else {
      topbar.appendChild(btn);
    }
  });
}

addToggle();

// CORRECAO: aplica o idioma salvo assim que o DOM estiver pronto.
// Antes, data-i18n so era processado no evento "langchange", entao um
// reload com EN/ES salvo exibia a interface estatica em portugues.
if(document.readyState === "loading"){
  document.addEventListener("DOMContentLoaded", function(){ syncHtmlLang(); applyStatic(); });
} else {
  syncHtmlLang(); applyStatic();
}

return { get:get, set:set, current:current, t:get, applyStatic:applyStatic };

})(); // end LANG

// Atalho global
function t(key){ return LANG.get(key); }

// Atalho global para reaplicar traducoes estaticas apos render dinamico
function tApply(root){ LANG.applyStatic(root); }
