// ── MAINTENX LANGUAGE MANAGER ─────────────────────────────────────────────
var LANG = (function(){

var TRANSLATIONS = {

// ── PORTUGUES (padrão) ──────────────────────────────────────────────────
pt: {
  // Navegação
  nav_dashboard:    "Dashboard",
  nav_ordens:       "Ordens de Servico",
  nav_ativos:       "Gestao de Ativos",
  nav_cadastros:    "Cadastros",
  nav_os:           "OS",
  nav_ativos_short: "Ativos",

  // Topbar
  topbar_alert_criticas: " OS critica(s) em aberto",

  // Dashboard — seções
  dash_status:      "Status Operacional",
  dash_confiab:     "Confiabilidade & Disponibilidade",
  dash_gestao:      "Gestao da Manutencao",
  dash_criticidade: "Criticidade dos Ativos (NORSOK Z-008 / API RP 581)",
  dash_ultimas_os:  "Ultimas Ordens",
  dash_equipamentos:"Equipamentos",
  dash_planos:      "Planos com Atencao",
  dash_ver_todas:   "Ver todas →",
  dash_calcular:    "Calcular na ficha do ativo →",
  dash_planos_ok:   "✓ Todos os planos em dia",

  // KPIs
  kpi_abertas:      "OS Abertas",
  kpi_andamento:    "Em Andamento",
  kpi_criticas:     "OS Criticas",
  kpi_equipamentos: "Equipamentos",
  kpi_mtbf:         "MTBF Global",
  kpi_mttr:         "MTTR Global",
  kpi_disponib:     "Disponib.",
  kpi_manuplan:     "Manut. Planejada",
  kpi_compliance:   "Compliance",
  kpi_backlog:      "Backlog",
  kpi_falhas:       "Falhas Corret.",
  kpi_aguardando:   "aguardando",
  kpi_em_exec:      "em execucao",
  kpi_prio_max:     "prioridade max",
  kpi_operando:     "operando",

  // Criticidade
  crit_matriz:      "Matriz de Risco (Consequencia x Probabilidade)",
  crit_ativos:      "Ativos por Criticidade",
  crit_eixo_y:      "Eixo Y: Consequencia",
  crit_eixo_x:      "Eixo X: Probabilidade",
  crit_score:       "Score de Criticidade (0-100)",
  crit_warn_super:  "% dos ativos classificados como Criticos — acima do limite de 30% (NORSOK Z-008). Recalibre os criterios.",
  crit_ok_bench:    "✓ Distribuicao dentro do benchmark (5-15% criticos) — NORSOK Z-008",
  crit_vazio:       'Abra a ficha de cada ativo e calcule a criticidade na aba "Criticidade".',
  crit_mais:        "+mais ",
  crit_avaliados:   " ativos avaliados",
  crit_classes:     {A:"Critico", B:"Alto", C:"Medio", D:"Baixo"},
  crit_recs: {
    A: "Monitoramento continuo (preditiva). Plano de contingencia obrigatorio. FMEA e analise de causa raiz.",
    B: "Preventiva sistematica. Monitoramento por condicao recomendado. Incluir no plano de inspecao.",
    C: "Preventiva baseada em tempo ou ciclos. Avaliar custo-beneficio de preditiva.",
    D: "Corretiva planejada aceitavel (run-to-failure). Garantir sobressalentes disponiveis."
  },

  // Ordens
  ord_titulo:       "Ordens de Servico",
  ord_nova:         "+ Nova OS",
  ord_filtro_todas: "Todas",
  ord_tipo_label:   "Tipo de Manutencao",
  ord_tipo_corr:    "Corretiva",
  ord_tipo_prev:    "Preventiva",
  ord_tipo_pred:    "Preditiva",
  ord_prio_label:   "Prioridade",
  ord_prio_crit:    "Critica",
  ord_prio_alta:    "Alta",
  ord_prio_normal:  "Normal",
  ord_prio_baixa:   "Baixa",
  ord_status_aberta:"Aberta",
  ord_status_and:   "Em Andamento",
  ord_status_conc:  "Concluida",
  ord_status_canc:  "Cancelada",
  ord_iniciar:      "▶ Iniciar Execucao",
  ord_registrar:    "+ Registrar Execucao",
  ord_concluir:     "✓ Concluir OS",
  ord_cancelar:     "✕ Cancelar",
  ord_finalizada:   "OS finalizada",
  ord_sem_prazo:    "Sem prazo",
  ord_atribuida_a:  "OS atribuida a",
  ord_periodo:      "Periodo",
  ord_proxima_em:   "Proxima OS em",
  ord_reg_exec:     "Registro de Execucao",
  ord_sem_reg:      "Nenhum registro ainda",
  ord_inicia_para_reg: "Inicie a OS para comecar a registrar",
  ord_total_pecas:  "em pecas",
  ord_nenhuma:      "Nenhuma OS encontrada",
  ord_nenhuma_cad:  "Nenhuma OS cadastrada",
  // Form labels
  ord_f_titulo:     "Titulo *",
  ord_f_ativo:      "Ativo *",
  ord_f_tipo:       "Tipo",
  ord_f_prio:       "Prioridade",
  ord_f_tecnico:    "Tecnico Responsavel",
  ord_f_prazo:      "Prazo",
  ord_f_periodo:    "Periodo (dias)",
  ord_f_proxima:    "Proxima OS em (dias)",
  ord_f_descricao:  "Descricao / Sintoma",
  ord_f_ativo_label:"Ativo",
  ord_f_abertura:   "Abertura",
  ord_f_tipo2:      "Tipo",
  // Exec log
  exec_tipo_obs:    "Observacao",
  exec_tipo_med:    "Medicao",
  exec_tipo_peca:   "Peca / Material",
  exec_tipo_foto:   "Foto",
  exec_param:       "Parametro medido",
  exec_valor:       "Valor medido *",
  exec_limite:      "Limite / Referencia",
  exec_cond:        "Condicao",
  exec_cond_normal: "Normal",
  exec_cond_atenc:  "Atencao",
  exec_cond_crit:   "Critico",
  exec_cond_fora:   "Fora de especificacao",
  exec_peca_desc:   "Descricao da Peca / Material *",
  exec_qty:         "Quantidade",
  exec_custo:       "Custo unitario (R$)",
  exec_foto_desc:   "Descricao da foto",
  exec_ultimo_reg:  "Ultimo registro",
  exec_qtd_reg:     " registros",

  // Ativos
  at_titulo:        "Gestao de Ativos",
  at_ficha:         "Ficha: ",
  at_novo:          "+ Novo Ativo",
  at_clique:        "Toque em um ativo para abrir a ficha completa",
  at_nenhum:        "Nenhum ativo cadastrado",
  at_tabs: {
    geral:         "Geral",
    indicadores:   "Indicadores",
    historico:     "Historico",
    preventiva:    "Plano de Manutencao",
    preditiva:     "Medicoes",
    documentos:    "Documentos",
    criticidade:   "Criticidade"
  },
  at_info_fabricante: "Fabricante",
  at_info_modelo:     "Modelo",
  at_info_serie:      "Serie",
  at_info_ano:        "Ano",
  at_info_local:      "Localizacao",
  at_info_cat:        "Categoria",
  at_info_tag:        "Tag",
  at_info_pat:        "Patrimonio",
  at_info_empresa:    "Empresa",
  at_info_unidade:    "Unidade",
  at_resumo:          "Resumo & Ultima Intervencao",
  at_intervencoes:    "Intervencoes",
  at_corretivas:      "Corretivas",
  at_horas:           "Horas em Manut.",
  at_ultima_int:      "Ultima Intervencao",
  at_sem_hist:        "Sem registros de manutencao",
  at_sel_ind:         "Selecionar Indicadores",
  at_sel_ind_sub:     "Clique para ativar ou desativar cada indicador neste equipamento.",
  at_nenhum_ind:      "Nenhum indicador ativado. Selecione abaixo.",
  at_reg_manut:       "+ Registrar Manutencao",
  at_registros:       " registro(s)",
  at_sem_manut:       "Nenhuma manutencao registrada ainda.",
  at_novo_plano:      "+ Novo Plano",
  at_nenhum_plano:    "Nenhum plano preventivo cadastrado",
  at_planos_atraso:   " plano(s) com atencao necessaria",
  at_nova_leitura:    "+ Nova Leitura",
  at_sem_leituras:    "Nenhuma leitura preditiva registrada.",
  at_mais_leituras:   "Adicione mais leituras para gerar o grafico",
  at_acima_limite:    "Ultimo valor acima do limite de alerta!",
  at_valor_med:       "Valor medido",
  at_limite:          "Limite",
  at_anexar:          "Clique para anexar documentos",
  at_anexar_sub:      "PDF, Word, Excel, Imagens, ZIP",
  at_sem_docs:        "Nenhum documento anexado",
  at_baixar:          "Baixar",
  at_status_op:       "Operacional",
  at_status_manut:    "Em Manutencao",
  at_status_par:      "Parado",
  // Analise de falha
  at_anal_titulo:     "Analise de Falha",
  at_anal_sem:        "Manutencao corretiva sem analise de falha",
  at_anal_add:        "+ Analise de Falha",
  at_anal_editar:     "editar",
  at_anal_salvar:     "Salvar Analise",
  at_anal_tipos: {
    "5porques": "5 Porques",
    "ishikawa":  "Ishikawa (6M)",
    "fmea":      "FMEA",
    "rca":       "RCA",
    "fta":       "Arvore de Falhas",
    "pdca":      "PDCA"
  },

  // Cadastros
  cad_titulo:         "Cadastros",
  cad_tab_usuarios:   "Usuarios",
  cad_tab_categorias: "Categorias",
  cad_tab_empresas:   "Empresas",
  cad_novo_user:      "+ Novo Usuario",
  cad_nova_cat:       "+ Nova Categoria",
  cad_nova_emp:       "+ Nova Empresa",
  cad_add_unid:       "+ Adicionar Unidade",
  cad_ativos_label:   " ativo(s)",
  cad_unidades_label: " unidade(s)",
  cad_inativar:       "Inativar",
  cad_ativar:         "Ativar",
  cad_excluir:        "Excluir",
  cad_nenhuma_emp:    "Nenhuma empresa cadastrada",
  cad_perfis: {
    Coordenador: "Coordenador",
    Tecnico:     "Tecnico",
    Visualizador:"Visualizador"
  },
  cad_f_nome:         "Nome completo *",
  cad_f_email:        "E-mail *",
  cad_f_telefone:     "Telefone",
  cad_f_senha:        "Senha",
  cad_f_perfil:       "Perfil",
  cad_f_status:       "Status",
  cad_f_ativo:        "✓ Ativo",
  cad_f_inativo:      "✕ Inativo",
  cad_f_cat_nome:     "Nome da Categoria *",
  cad_f_cat_desc:     "Descricao",
  cad_f_cat_icone:    "Icone",
  cad_f_cat_cor:      "Cor",
  cad_f_cat_prev:     "Preview",
  cad_f_emp_nome:     "Razao Social / Nome *",
  cad_f_emp_cnpj:     "CNPJ",
  cad_f_emp_tel:      "Telefone",
  cad_f_emp_end:      "Endereco",
  cad_f_emp_cont:     "Contato responsavel",
  cad_f_unid_nome:    "Nome da Unidade *",
  cad_f_unid_end:     "Endereco / Localizacao",
  cad_f_unid_resp:    "Responsavel",

  // Form campos ativos
  at_f_nome:          "Nome *",
  at_f_cat:           "Categoria",
  at_f_empresa:       "Empresa",
  at_f_unidade:       "Unidade",
  at_f_local:         "Localizacao",
  at_f_fab:           "Fabricante",
  at_f_modelo:        "Modelo",
  at_f_serie:         "Serie",
  at_f_ano:           "Ano",
  at_f_tag:           "Tag",
  at_f_pat:           "Patrimonio",

  // Histórico form
  h_f_desc:           "Descricao *",
  h_f_data:           "Data",
  h_f_tipo:           "Tipo",
  h_f_tecnico:        "Tecnico",
  h_f_horas:          "Horas",
  h_f_custo:          "Custo (R$)",
  h_f_prox:           "Proximo (dias)",
  h_f_obs:            "Observacoes",

  // Plano form
  pl_f_nome:          "Nome *",
  pl_f_freq:          "Frequencia",
  pl_f_prox:          "Proxima Execucao",
  pl_f_resp:          "Responsavel",
  pl_freq: {
    Semanal:"Semanal", Quinzenal:"Quinzenal", Mensal:"Mensal",
    Bimestral:"Bimestral", Trimestral:"Trimestral",
    Semestral:"Semestral", Anual:"Anual"
  },

  // Plano status
  pl_ok:              "OK",
  pl_atrasado:        "Atrasado",
  pl_vence:           "Vence Hoje",
  pl_todos_ok:        "✓ Todos os planos em dia",
  pl_nenhuma_os:      "Nenhuma OS cadastrada",

  // Indicadores
  ind_names: {
    mtbf:"Tempo Medio entre Falhas", mttr:"Tempo Medio de Reparo",
    disp:"Disponibilidade", conf:"Confiabilidade 1000h",
    lambda:"Taxa de Falhas", manuplan:"Manutencao Planejada",
    backlog:"Backlog de OS", nfalhas:"Numero de Falhas",
    compliance:"Compliance Preventivo", mttf:"Tempo Medio ate Falha",
    downtime:"Horas Indisponivel", oee_a:"Disponibilidade OEE"
  },
  ind_abbrs: {
    mtbf:"MTBF", mttr:"MTTR", disp:"A(%)", conf:"R(t)",
    lambda:"Txa-F", manuplan:"MP%", backlog:"BKL",
    nfalhas:"NF", compliance:"CP%", mttf:"MTTF",
    downtime:"DT", oee_a:"OEE-A"
  },

  // Botões comuns
  btn_salvar:    "Salvar",
  btn_cancelar:  "Cancelar",
  btn_editar:    "Editar",
  btn_excluir:   "Excluir",
  btn_voltar:    "← Voltar",
  btn_novo:      "+ Novo",
  btn_cadastrar: "Cadastrar",
  btn_criar_os:  "Criar OS",
  btn_selecione: "Selecione...",
  btn_sel_emp:   "Selecione a empresa...",
  btn_sel_unid:  "Selecione a unidade...",
  btn_sem_emp:   "Nenhuma empresa cadastrada",
},

// ── ENGLISH ────────────────────────────────────────────────────────────────
en: {
  nav_dashboard:    "Dashboard",
  nav_ordens:       "Work Orders",
  nav_ativos:       "Asset Management",
  nav_cadastros:    "Settings",
  nav_os:           "WO",
  nav_ativos_short: "Assets",

  topbar_alert_criticas: " critical WO(s) open",

  dash_status:      "Operational Status",
  dash_confiab:     "Reliability & Availability",
  dash_gestao:      "Maintenance Management",
  dash_criticidade: "Asset Criticality (NORSOK Z-008 / API RP 581)",
  dash_ultimas_os:  "Latest Work Orders",
  dash_equipamentos:"Equipment",
  dash_planos:      "Attention Required",
  dash_ver_todas:   "View all →",
  dash_calcular:    "Calculate in asset sheet →",
  dash_planos_ok:   "✓ All plans on schedule",

  kpi_abertas:      "Open WOs",
  kpi_andamento:    "In Progress",
  kpi_criticas:     "Critical WOs",
  kpi_equipamentos: "Equipment",
  kpi_mtbf:         "Global MTBF",
  kpi_mttr:         "Global MTTR",
  kpi_disponib:     "Avail.",
  kpi_manuplan:     "Planned Maint.",
  kpi_compliance:   "Compliance",
  kpi_backlog:      "Backlog",
  kpi_falhas:       "Corrective Fail.",
  kpi_aguardando:   "waiting",
  kpi_em_exec:      "in progress",
  kpi_prio_max:     "max priority",
  kpi_operando:     "running",

  crit_matriz:      "Risk Matrix (Consequence x Probability)",
  crit_ativos:      "Assets by Criticality",
  crit_eixo_y:      "Y-Axis: Consequence",
  crit_eixo_x:      "X-Axis: Probability",
  crit_score:       "Criticality Score (0-100)",
  crit_warn_super:  "% of assets classified as Critical — above 30% limit (NORSOK Z-008). Recalibrate criteria.",
  crit_ok_bench:    "✓ Distribution within benchmark (5-15% critical) — NORSOK Z-008",
  crit_vazio:       'Open each asset sheet and calculate criticality in the "Criticality" tab.',
  crit_mais:        "+more ",
  crit_avaliados:   " assets evaluated",
  crit_classes:     {A:"Critical", B:"High", C:"Medium", D:"Low"},
  crit_recs: {
    A: "Continuous monitoring (predictive). Mandatory contingency plan. FMEA and root cause analysis.",
    B: "Systematic preventive maintenance. Condition monitoring recommended. Include in inspection plan.",
    C: "Time/cycle-based preventive maintenance. Evaluate predictive cost-benefit.",
    D: "Planned corrective maintenance acceptable (run-to-failure). Ensure spare parts available."
  },

  ord_titulo:       "Work Orders",
  ord_nova:         "+ New WO",
  ord_filtro_todas: "All",
  ord_tipo_label:   "Maintenance Type",
  ord_tipo_corr:    "Corrective",
  ord_tipo_prev:    "Preventive",
  ord_tipo_pred:    "Predictive",
  ord_prio_label:   "Priority",
  ord_prio_crit:    "Critical",
  ord_prio_alta:    "High",
  ord_prio_normal:  "Normal",
  ord_prio_baixa:   "Low",
  ord_status_aberta:"Open",
  ord_status_and:   "In Progress",
  ord_status_conc:  "Completed",
  ord_status_canc:  "Cancelled",
  ord_iniciar:      "▶ Start Execution",
  ord_registrar:    "+ Log Activity",
  ord_concluir:     "✓ Complete WO",
  ord_cancelar:     "✕ Cancel",
  ord_finalizada:   "WO closed",
  ord_sem_prazo:    "No deadline",
  ord_atribuida_a:  "WO assigned to",
  ord_periodo:      "Period",
  ord_proxima_em:   "Next WO in",
  ord_reg_exec:     "Execution Log",
  ord_sem_reg:      "No records yet",
  ord_inicia_para_reg: "Start WO to begin logging",
  ord_total_pecas:  "in parts",
  ord_nenhuma:      "No work orders found",
  ord_nenhuma_cad:  "No work orders registered",
  ord_f_titulo:     "Title *",
  ord_f_ativo:      "Asset *",
  ord_f_tipo:       "Type",
  ord_f_prio:       "Priority",
  ord_f_tecnico:    "Assigned Technician",
  ord_f_prazo:      "Deadline",
  ord_f_periodo:    "Period (days)",
  ord_f_proxima:    "Next WO in (days)",
  ord_f_descricao:  "Description / Symptom",
  ord_f_ativo_label:"Asset",
  ord_f_abertura:   "Opened",
  ord_f_tipo2:      "Type",
  exec_tipo_obs:    "Observation",
  exec_tipo_med:    "Measurement",
  exec_tipo_peca:   "Part / Material",
  exec_tipo_foto:   "Photo",
  exec_param:       "Measured parameter",
  exec_valor:       "Measured value *",
  exec_limite:      "Limit / Reference",
  exec_cond:        "Condition",
  exec_cond_normal: "Normal",
  exec_cond_atenc:  "Warning",
  exec_cond_crit:   "Critical",
  exec_cond_fora:   "Out of spec",
  exec_peca_desc:   "Part / Material description *",
  exec_qty:         "Quantity",
  exec_custo:       "Unit cost ($)",
  exec_foto_desc:   "Photo description",
  exec_ultimo_reg:  "Last entry",
  exec_qtd_reg:     " records",

  at_titulo:        "Asset Management",
  at_ficha:         "Sheet: ",
  at_novo:          "+ New Asset",
  at_clique:        "Tap an asset to open its full sheet",
  at_nenhum:        "No assets registered",
  at_tabs: {
    geral:"General", indicadores:"Indicators", historico:"History",
    preventiva:"Maint. Plan", preditiva:"Measurements",
    documentos:"Documents", criticidade:"Criticality"
  },
  at_info_fabricante:"Manufacturer",
  at_info_modelo:    "Model",
  at_info_serie:     "Serial No.",
  at_info_ano:       "Year",
  at_info_local:     "Location",
  at_info_cat:       "Category",
  at_info_tag:       "Tag",
  at_info_pat:       "Asset No.",
  at_info_empresa:   "Company",
  at_info_unidade:   "Unit",
  at_resumo:         "Summary & Last Intervention",
  at_intervencoes:   "Interventions",
  at_corretivas:     "Corrective",
  at_horas:          "Maint. Hours",
  at_ultima_int:     "Last Intervention",
  at_sem_hist:       "No maintenance records",
  at_sel_ind:        "Select Indicators",
  at_sel_ind_sub:    "Click to enable or disable each indicator for this asset.",
  at_nenhum_ind:     "No indicators enabled. Select below.",
  at_reg_manut:      "+ Log Maintenance",
  at_registros:      " record(s)",
  at_sem_manut:      "No maintenance logged yet.",
  at_novo_plano:     "+ New Plan",
  at_nenhum_plano:   "No preventive plans registered",
  at_planos_atraso:  " plan(s) require attention",
  at_nova_leitura:   "+ New Reading",
  at_sem_leituras:   "No predictive readings registered.",
  at_mais_leituras:  "Add more readings to generate chart",
  at_acima_limite:   "Last value above alert limit!",
  at_valor_med:      "Measured value",
  at_limite:         "Limit",
  at_anexar:         "Click to attach documents",
  at_anexar_sub:     "PDF, Word, Excel, Images, ZIP",
  at_sem_docs:       "No documents attached",
  at_baixar:         "Download",
  at_status_op:      "Operational",
  at_status_manut:   "Under Maintenance",
  at_status_par:     "Stopped",
  at_anal_titulo:    "Failure Analysis",
  at_anal_sem:       "Corrective maintenance without failure analysis",
  at_anal_add:       "+ Failure Analysis",
  at_anal_editar:    "edit",
  at_anal_salvar:    "Save Analysis",
  at_anal_tipos: {
    "5porques":"5 Whys", "ishikawa":"Ishikawa (6M)",
    "fmea":"FMEA", "rca":"RCA",
    "fta":"Fault Tree", "pdca":"PDCA"
  },

  cad_titulo:         "Settings",
  cad_tab_usuarios:   "Users",
  cad_tab_categorias: "Categories",
  cad_tab_empresas:   "Companies",
  cad_novo_user:      "+ New User",
  cad_nova_cat:       "+ New Category",
  cad_nova_emp:       "+ New Company",
  cad_add_unid:       "+ Add Unit",
  cad_ativos_label:   " asset(s)",
  cad_unidades_label: " unit(s)",
  cad_inativar:       "Deactivate",
  cad_ativar:         "Activate",
  cad_excluir:        "Delete",
  cad_nenhuma_emp:    "No companies registered",
  cad_perfis: {Coordenador:"Coordinator", Tecnico:"Technician", Visualizador:"Viewer"},
  cad_f_nome:         "Full name *",
  cad_f_email:        "E-mail *",
  cad_f_telefone:     "Phone",
  cad_f_senha:        "Password",
  cad_f_perfil:       "Role",
  cad_f_status:       "Status",
  cad_f_ativo:        "✓ Active",
  cad_f_inativo:      "✕ Inactive",
  cad_f_cat_nome:     "Category name *",
  cad_f_cat_desc:     "Description",
  cad_f_cat_icone:    "Icon",
  cad_f_cat_cor:      "Color",
  cad_f_cat_prev:     "Preview",
  cad_f_emp_nome:     "Company name *",
  cad_f_emp_cnpj:     "Tax ID",
  cad_f_emp_tel:      "Phone",
  cad_f_emp_end:      "Address",
  cad_f_emp_cont:     "Contact person",
  cad_f_unid_nome:    "Unit name *",
  cad_f_unid_end:     "Address / Location",
  cad_f_unid_resp:    "Responsible",

  at_f_nome:"Name *", at_f_cat:"Category", at_f_empresa:"Company",
  at_f_unidade:"Unit", at_f_local:"Location", at_f_fab:"Manufacturer",
  at_f_modelo:"Model", at_f_serie:"Serial No.", at_f_ano:"Year",
  at_f_tag:"Tag", at_f_pat:"Asset No.",

  h_f_desc:"Description *", h_f_data:"Date", h_f_tipo:"Type",
  h_f_tecnico:"Technician", h_f_horas:"Hours", h_f_custo:"Cost ($)",
  h_f_prox:"Next (days)", h_f_obs:"Notes",

  pl_f_nome:"Name *", pl_f_freq:"Frequency",
  pl_f_prox:"Next Execution", pl_f_resp:"Responsible",
  pl_freq: {
    Semanal:"Weekly", Quinzenal:"Biweekly", Mensal:"Monthly",
    Bimestral:"Bimonthly", Trimestral:"Quarterly",
    Semestral:"Semiannual", Anual:"Annual"
  },
  pl_ok:"OK", pl_atrasado:"Overdue", pl_vence:"Due Today",
  pl_todos_ok:"✓ All plans on schedule",
  pl_nenhuma_os:"No work orders registered",

  ind_names: {
    mtbf:"Mean Time Between Failures", mttr:"Mean Time To Repair",
    disp:"Availability", conf:"Reliability 1000h",
    lambda:"Failure Rate", manuplan:"Planned Maintenance",
    backlog:"WO Backlog", nfalhas:"Failure Count",
    compliance:"Preventive Compliance", mttf:"Mean Time To Failure",
    downtime:"Downtime Hours", oee_a:"OEE Availability"
  },
  ind_abbrs: {
    mtbf:"MTBF", mttr:"MTTR", disp:"A(%)", conf:"R(t)",
    lambda:"F-Rate", manuplan:"PM%", backlog:"BKL",
    nfalhas:"FC", compliance:"PC%", mttf:"MTTF",
    downtime:"DT", oee_a:"OEE-A"
  },

  btn_salvar:"Save", btn_cancelar:"Cancel", btn_editar:"Edit",
  btn_excluir:"Delete", btn_voltar:"← Back", btn_novo:"+ New",
  btn_cadastrar:"Register", btn_criar_os:"Create WO",
  btn_selecione:"Select...", btn_sel_emp:"Select company...",
  btn_sel_unid:"Select unit...", btn_sem_emp:"No companies registered",
},

// ── ESPAÑOL ────────────────────────────────────────────────────────────────
es: {
  nav_dashboard:    "Panel",
  nav_ordens:       "Ordenes de Trabajo",
  nav_ativos:       "Gestion de Activos",
  nav_cadastros:    "Configuracion",
  nav_os:           "OT",
  nav_ativos_short: "Activos",

  topbar_alert_criticas: " OT critica(s) abiertas",

  dash_status:      "Estado Operacional",
  dash_confiab:     "Confiabilidad y Disponibilidad",
  dash_gestao:      "Gestion del Mantenimiento",
  dash_criticidade: "Criticidad de Activos (NORSOK Z-008 / API RP 581)",
  dash_ultimas_os:  "Ultimas Ordenes de Trabajo",
  dash_equipamentos:"Equipos",
  dash_planos:      "Atencion Requerida",
  dash_ver_todas:   "Ver todas →",
  dash_calcular:    "Calcular en la ficha del activo →",
  dash_planos_ok:   "✓ Todos los planes al dia",

  kpi_abertas:      "OT Abiertas",
  kpi_andamento:    "En Progreso",
  kpi_criticas:     "OT Criticas",
  kpi_equipamentos: "Equipos",
  kpi_mtbf:         "MTBF Global",
  kpi_mttr:         "MTTR Global",
  kpi_disponib:     "Dispon.",
  kpi_manuplan:     "Mant. Planificado",
  kpi_compliance:   "Cumplimiento",
  kpi_backlog:      "Backlog",
  kpi_falhas:       "Fallos Correct.",
  kpi_aguardando:   "esperando",
  kpi_em_exec:      "en progreso",
  kpi_prio_max:     "prioridad max",
  kpi_operando:     "funcionando",

  crit_matriz:      "Matriz de Riesgo (Consecuencia x Probabilidad)",
  crit_ativos:      "Activos por Criticidad",
  crit_eixo_y:      "Eje Y: Consecuencia",
  crit_eixo_x:      "Eje X: Probabilidad",
  crit_score:       "Puntuacion de Criticidad (0-100)",
  crit_warn_super:  "% de activos clasificados como Criticos — por encima del limite del 30% (NORSOK Z-008). Recalibrar criterios.",
  crit_ok_bench:    "✓ Distribucion dentro del benchmark (5-15% criticos) — NORSOK Z-008",
  crit_vazio:       'Abra la ficha de cada activo y calcule la criticidad en la pestana "Criticidad".',
  crit_mais:        "+mas ",
  crit_avaliados:   " activos evaluados",
  crit_classes:     {A:"Critico", B:"Alto", C:"Medio", D:"Bajo"},
  crit_recs: {
    A: "Monitoreo continuo (predictivo). Plan de contingencia obligatorio. FMEA y analisis de causa raiz.",
    B: "Mantenimiento preventivo sistematico. Monitoreo por condicion recomendado.",
    C: "Preventivo basado en tiempo o ciclos. Evaluar costo-beneficio predictivo.",
    D: "Correctivo planificado aceptable (run-to-failure). Garantizar repuestos disponibles."
  },

  ord_titulo:       "Ordenes de Trabajo",
  ord_nova:         "+ Nueva OT",
  ord_filtro_todas: "Todas",
  ord_tipo_label:   "Tipo de Mantenimiento",
  ord_tipo_corr:    "Correctivo",
  ord_tipo_prev:    "Preventivo",
  ord_tipo_pred:    "Predictivo",
  ord_prio_label:   "Prioridad",
  ord_prio_crit:    "Critica",
  ord_prio_alta:    "Alta",
  ord_prio_normal:  "Normal",
  ord_prio_baixa:   "Baja",
  ord_status_aberta:"Abierta",
  ord_status_and:   "En Progreso",
  ord_status_conc:  "Completada",
  ord_status_canc:  "Cancelada",
  ord_iniciar:      "▶ Iniciar Ejecucion",
  ord_registrar:    "+ Registrar Actividad",
  ord_concluir:     "✓ Completar OT",
  ord_cancelar:     "✕ Cancelar",
  ord_finalizada:   "OT cerrada",
  ord_sem_prazo:    "Sin fecha limite",
  ord_atribuida_a:  "OT asignada a",
  ord_periodo:      "Periodo",
  ord_proxima_em:   "Proxima OT en",
  ord_reg_exec:     "Registro de Ejecucion",
  ord_sem_reg:      "Sin registros aun",
  ord_inicia_para_reg:"Inicie la OT para comenzar a registrar",
  ord_total_pecas:  "en piezas",
  ord_nenhuma:      "Ninguna OT encontrada",
  ord_nenhuma_cad:  "Ninguna OT registrada",
  ord_f_titulo:     "Titulo *",
  ord_f_ativo:      "Activo *",
  ord_f_tipo:       "Tipo",
  ord_f_prio:       "Prioridad",
  ord_f_tecnico:    "Tecnico Asignado",
  ord_f_prazo:      "Fecha limite",
  ord_f_periodo:    "Periodo (dias)",
  ord_f_proxima:    "Proxima OT en (dias)",
  ord_f_descricao:  "Descripcion / Sintoma",
  ord_f_ativo_label:"Activo",
  ord_f_abertura:   "Apertura",
  ord_f_tipo2:      "Tipo",
  exec_tipo_obs:    "Observacion",
  exec_tipo_med:    "Medicion",
  exec_tipo_peca:   "Pieza / Material",
  exec_tipo_foto:   "Foto",
  exec_param:       "Parametro medido",
  exec_valor:       "Valor medido *",
  exec_limite:      "Limite / Referencia",
  exec_cond:        "Condicion",
  exec_cond_normal: "Normal",
  exec_cond_atenc:  "Atencion",
  exec_cond_crit:   "Critico",
  exec_cond_fora:   "Fuera de especificacion",
  exec_peca_desc:   "Descripcion de la pieza *",
  exec_qty:         "Cantidad",
  exec_custo:       "Costo unitario ($)",
  exec_foto_desc:   "Descripcion de la foto",
  exec_ultimo_reg:  "Ultimo registro",
  exec_qtd_reg:     " registros",

  at_titulo:        "Gestion de Activos",
  at_ficha:         "Ficha: ",
  at_novo:          "+ Nuevo Activo",
  at_clique:        "Toque un activo para abrir su ficha",
  at_nenhum:        "Ningun activo registrado",
  at_tabs: {
    geral:"General", indicadores:"Indicadores", historico:"Historial",
    preventiva:"Plan de Mantenimiento", preditiva:"Mediciones",
    documentos:"Documentos", criticidade:"Criticidad"
  },
  at_info_fabricante:"Fabricante",
  at_info_modelo:    "Modelo",
  at_info_serie:     "N° Serie",
  at_info_ano:       "Ano",
  at_info_local:     "Ubicacion",
  at_info_cat:       "Categoria",
  at_info_tag:       "Tag",
  at_info_pat:       "N° Patrimonio",
  at_info_empresa:   "Empresa",
  at_info_unidade:   "Unidad",
  at_resumo:         "Resumen y Ultima Intervencion",
  at_intervencoes:   "Intervenciones",
  at_corretivas:     "Correctivos",
  at_horas:          "Horas de Mant.",
  at_ultima_int:     "Ultima Intervencion",
  at_sem_hist:       "Sin registros de mantenimiento",
  at_sel_ind:        "Seleccionar Indicadores",
  at_sel_ind_sub:    "Haga clic para activar o desactivar cada indicador.",
  at_nenhum_ind:     "Ningun indicador activado. Seleccione abajo.",
  at_reg_manut:      "+ Registrar Mantenimiento",
  at_registros:      " registro(s)",
  at_sem_manut:      "Ningun mantenimiento registrado aun.",
  at_novo_plano:     "+ Nuevo Plan",
  at_nenhum_plano:   "Ningun plan preventivo registrado",
  at_planos_atraso:  " plan(es) requieren atencion",
  at_nova_leitura:   "+ Nueva Lectura",
  at_sem_leituras:   "Ninguna lectura predictiva registrada.",
  at_mais_leituras:  "Agregue mas lecturas para generar el grafico",
  at_acima_limite:   "Ultimo valor por encima del limite de alerta!",
  at_valor_med:      "Valor medido",
  at_limite:         "Limite",
  at_anexar:         "Haga clic para adjuntar documentos",
  at_anexar_sub:     "PDF, Word, Excel, Imagenes, ZIP",
  at_sem_docs:       "Ningun documento adjunto",
  at_baixar:         "Descargar",
  at_status_op:      "Operacional",
  at_status_manut:   "En Mantenimiento",
  at_status_par:     "Parado",
  at_anal_titulo:    "Analisis de Falla",
  at_anal_sem:       "Mantenimiento correctivo sin analisis de falla",
  at_anal_add:       "+ Analisis de Falla",
  at_anal_editar:    "editar",
  at_anal_salvar:    "Guardar Analisis",
  at_anal_tipos: {
    "5porques":"5 Por Ques", "ishikawa":"Ishikawa (6M)",
    "fmea":"FMEA", "rca":"RCA",
    "fta":"Arbol de Fallos", "pdca":"PDCA"
  },

  cad_titulo:         "Configuracion",
  cad_tab_usuarios:   "Usuarios",
  cad_tab_categorias: "Categorias",
  cad_tab_empresas:   "Empresas",
  cad_novo_user:      "+ Nuevo Usuario",
  cad_nova_cat:       "+ Nueva Categoria",
  cad_nova_emp:       "+ Nueva Empresa",
  cad_add_unid:       "+ Agregar Unidad",
  cad_ativos_label:   " activo(s)",
  cad_unidades_label: " unidad(es)",
  cad_inativar:       "Desactivar",
  cad_ativar:         "Activar",
  cad_excluir:        "Eliminar",
  cad_nenhuma_emp:    "Ninguna empresa registrada",
  cad_perfis: {Coordenador:"Coordinador", Tecnico:"Tecnico", Visualizador:"Visualizador"},
  cad_f_nome:         "Nombre completo *",
  cad_f_email:        "Correo electronico *",
  cad_f_telefone:     "Telefono",
  cad_f_senha:        "Contrasena",
  cad_f_perfil:       "Perfil",
  cad_f_status:       "Estado",
  cad_f_ativo:        "✓ Activo",
  cad_f_inativo:      "✕ Inactivo",
  cad_f_cat_nome:     "Nombre de la categoria *",
  cad_f_cat_desc:     "Descripcion",
  cad_f_cat_icone:    "Icono",
  cad_f_cat_cor:      "Color",
  cad_f_cat_prev:     "Vista previa",
  cad_f_emp_nome:     "Nombre / Razon social *",
  cad_f_emp_cnpj:     "ID Fiscal",
  cad_f_emp_tel:      "Telefono",
  cad_f_emp_end:      "Direccion",
  cad_f_emp_cont:     "Persona de contacto",
  cad_f_unid_nome:    "Nombre de la unidad *",
  cad_f_unid_end:     "Direccion / Ubicacion",
  cad_f_unid_resp:    "Responsable",

  at_f_nome:"Nombre *", at_f_cat:"Categoria", at_f_empresa:"Empresa",
  at_f_unidade:"Unidad", at_f_local:"Ubicacion", at_f_fab:"Fabricante",
  at_f_modelo:"Modelo", at_f_serie:"N° Serie", at_f_ano:"Ano",
  at_f_tag:"Tag", at_f_pat:"N° Patrimonio",

  h_f_desc:"Descripcion *", h_f_data:"Fecha", h_f_tipo:"Tipo",
  h_f_tecnico:"Tecnico", h_f_horas:"Horas", h_f_custo:"Costo ($)",
  h_f_prox:"Proximo (dias)", h_f_obs:"Observaciones",

  pl_f_nome:"Nombre *", pl_f_freq:"Frecuencia",
  pl_f_prox:"Proxima Ejecucion", pl_f_resp:"Responsable",
  pl_freq: {
    Semanal:"Semanal", Quinzenal:"Quincenal", Mensal:"Mensual",
    Bimestral:"Bimestral", Trimestral:"Trimestral",
    Semestral:"Semestral", Anual:"Anual"
  },
  pl_ok:"OK", pl_atrasado:"Atrasado", pl_vence:"Vence Hoy",
  pl_todos_ok:"✓ Todos los planes al dia",
  pl_nenhuma_os:"Ninguna orden registrada",

  ind_names: {
    mtbf:"Tiempo Medio entre Fallos", mttr:"Tiempo Medio de Reparacion",
    disp:"Disponibilidad", conf:"Confiabilidad 1000h",
    lambda:"Tasa de Fallos", manuplan:"Mantenimiento Planificado",
    backlog:"Backlog de OT", nfalhas:"Numero de Fallos",
    compliance:"Cumplimiento Preventivo", mttf:"Tiempo Medio hasta Fallo",
    downtime:"Horas Inactivas", oee_a:"Disponibilidad OEE"
  },
  ind_abbrs: {
    mtbf:"MTBF", mttr:"MTTR", disp:"D(%)", conf:"R(t)",
    lambda:"Tasa-F", manuplan:"MP%", backlog:"BKL",
    nfalhas:"NF", compliance:"CP%", mttf:"MTTF",
    downtime:"DT", oee_a:"OEE-D"
  },

  btn_salvar:"Guardar", btn_cancelar:"Cancelar", btn_editar:"Editar",
  btn_excluir:"Eliminar", btn_voltar:"← Volver", btn_novo:"+ Nuevo",
  btn_cadastrar:"Registrar", btn_criar_os:"Crear OT",
  btn_selecione:"Seleccione...", btn_sel_emp:"Seleccione empresa...",
  btn_sel_unid:"Seleccione unidad...", btn_sem_emp:"Ninguna empresa registrada",
}

}; // end TRANSLATIONS

// ── API PÚBLICA ──────────────────────────────────────────────────────────────
var LANG_KEY = "mx_lang";
var _current  = localStorage.getItem(LANG_KEY) || "pt";

function get(key){
  var d = TRANSLATIONS[_current] || TRANSLATIONS["pt"];
  return d[key] !== undefined ? d[key] : (TRANSLATIONS["pt"][key] || key);
}

function current(){ return _current; }

function set(lang){
  if(!TRANSLATIONS[lang]) return;
  _current = lang;
  localStorage.setItem(LANG_KEY, lang);
}

function addToggle(){
  document.addEventListener("DOMContentLoaded", function(){
    var topbar = document.getElementById("topbar");
    if(!topbar) return;

    var btn = document.createElement("button");
    btn.id    = "lang-btn";
    btn.title = "Change language / Idioma";
    btn.style.cssText = [
      "background:transparent",
      "border:1px solid var(--border,#1e3a5f)",
      "border-radius:8px",
      "padding:5px 9px",
      "cursor:pointer",
      "font-size:12px",
      "font-weight:700",
      "letter-spacing:.03em",
      "transition:all .2s",
      "flex-shrink:0",
      "color:inherit"
    ].join(";");

    var LABELS = {pt:"PT", en:"EN", es:"ES"};
    var ORDER  = ["pt","en","es"];

    function update(){
      btn.textContent = LABELS[_current] || _current.toUpperCase();
    }
    update();

    btn.onclick = function(){
      var idx  = ORDER.indexOf(_current);
      var next = ORDER[(idx + 1) % ORDER.length];
      set(next);
      update();
      // Dispara evento para que os HTMLs possam re-renderizar
      window.dispatchEvent(new CustomEvent("langchange", {detail:{lang:next}}));
    };

    // Insere antes do botao de logout, para que o logout fique sempre
    // como o ultimo item (mais a direita) do topbar
    var logoutBtn = document.getElementById("logout-btn");
    if(logoutBtn && logoutBtn.parentNode === topbar){
      topbar.insertBefore(btn, logoutBtn);
    } else {
      topbar.appendChild(btn);
    }
  });
}

addToggle();

return { get:get, set:set, current:current, t:get };

})(); // end LANG

// Atalho global
function t(key){ return LANG.get(key); }
